### PR TITLE
Don't use pandas' .str.encode()

### PR DESCRIPTION
**Pull request by martindurant**
Related to https://github.com/dask/dask/pull/1860

### CODE REVIEW

**Comment by martindurant** [comment]
Causes speed-up in writing utf8 columns from
```
utf8: write, fixed: 6 517.728
utf8: write, fixed: None 900.611
```
to
```
utf8: write, fixed: 6 266.408
utf8: write, fixed: None 650.67
```
(1M items)

**Comment by pitrou** [comment]
Be careful that `.encode()` without arguments will only use utf8 by default on Python 3. On Python 2, it will use whatever is the "default encoding".
Given the tests pass, I assume you're only testing with ASCII content?

**Comment by martindurant** [comment]
This code it py3 only for the time being. Good to keep that in mind for the future, if I get around to making py2 compatibility.

**Comment by mrocklin** [comment]
It would be nice to have unicode text in tests regardless.

**Comment by TomAugspurger** [comment]
I haven't looked closely, so forgive me if this is a silly question: is it possible for there to be missing values (`nan`) in `data`? If so, does this code handle them? That's part of the reason for the overhead in pandas `.str.encode`.

**Comment by mrocklin** [comment]
Might be worth trying the fast thing first and then reverting to the slow approach if that fails.  Regardless we should probably test for this case?

**Comment by martindurant** [comment]
NULLs (None) are accounted for at a higher level - they don't get encoded into the data, but into a separate "definition levels" block, especially for types like this that have no inherent representation (unlike NaN for floats). If the user specifies has_nulls=False (i.e., don't write the nulls block), but there are some, you get an error.

**Pull request merged**
