### PR TITLE
CI: Speed up pandas ci and skip some tests

### PR DESCRIPTION
**Pull request by lithomas1**

### CODE REVIEW

**Comment by martindurant** [comment]
```
FAILED pandas/pandas/tests/io/test_parquet.py::test_cross_engine_fp_pa - Asse...
FAILED pandas/pandas/tests/io/test_parquet.py::TestParquetFastParquet::test_bool_with_none
```

**Comment by martindurant** [comment]
> For the nullable types, you need to make a new release before we can use them, so the test is expected to fail.

I am surprised - why are we not testing against the current code version? Do you mean that changes required within pandas can only happen after a fastparquet version to apply them to?

**Comment by martindurant** [comment]
Pushing this in too - let's iterate to fix everything for a release.

**Comment by lithomas1** [comment]
> I am surprised - why are we not testing against the current code version? Do you mean that changes required within pandas can only happen after a fastparquet version to apply them to?

Yes, pandas only tests against release versions of fastparquet, so we would need a new fastparquet release. The only thing that we test the dev version of is numpy.

**Comment by martindurant** [comment]
Wouldn't it make more sense to test dev fastparquet versus dev pandas in this repo? That way I can know if a change will break pandas *before* releasing it.

**Comment by lithomas1** [comment]
dev fastparquet versus dev pandas is tested in this repo, though.
fastparquet is installed from source on this line. (We cloned this repo above in checkout step).
https://github.com/dask/fastparquet/blob/a2b3c8c7b0954e9611a9037969472ba420d69ebe/.github/workflows/main.yaml#L130

Dev pandas is installed here.
https://github.com/dask/fastparquet/blob/a2b3c8c7b0954e9611a9037969472ba420d69ebe/.github/workflows/main.yaml#L131-L134


I know that this works since we used to have 3 failing tests, but you fixed one, which reflected on CI. I'll xfail the other cross compat test between fastparquet writing and pyarrow reading in the main pandas repo(which will get rid of that failure), and the last one we need fastparquet to release another minor version, so we can incorporate nullable dtypes into pandas and fix the last test.

**Pull request merged**
