### PR TITLE
Very special case for partition: NOW should be kept as string

### LINKED ISSUE #149: Writing large frame with partition_on= used adds timestamp of creation time to partitions, breaks filters=
Hello - 

Related to #148 , but different issue.  I'm trying to re-create without posting ~1GB of data to the issue, but haven't been able to.

I have a ~2.7GB dataframe which I am trying to write to a partitioned parquet hive repository.  Command used below:
```python
pq.write('pqPartitioned', df, partition_on=['UnderlyingSymbol'], file_scheme='hive')
```

After it is successfully written and I run ```pq.ParquetFile('pqPartitioned').cats```, there is a timestamp of the creation time as one of the cats or partition keys.

This then breaks the filter_on= capability of to_pandas() function.

Further, even if I try to read the whole frame with ```pq.ParquetFile('pqPartitioned').to_pandas``` I get the below error:
```python
ValueError: Timestamp('2017-05-14 12:47:10') is not in list
```

I checked:
* input dataframe doesn't include any timestamps in the 'UnderlyingSymbol' column before being written
* tried this with original dataframe index intact as well as with index reset
* using fastparquet 0.0.6

I will keep trying to recreating this with my test dataframe generator so this can be recreated in other environments, but I think these two facts may indicate something is going on internally to fastparquet: 
1) the input dataframe column is definitively clean without timestamps
2) the timestamp inserted is consistent with the time the parquet hive tree was created

Any ideas would be appreciated!

Thanks -

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #149

### CODE REVIEW

**Comment by canada4663** [comment]
This should solve it!

The additional corner case is any string with a reserved character in it - such as -, +, !, %, * also were failing on eval.  I had stripped them out of my dataset manually.

I believe your change to the api function should solve this as you are testing if val is a 'str' and if so, bypassing val_to_num.

I will try my original test dataframe with this lib tonight.

**Comment by canada4663** [comment]
I *think* it is fixed, however, I am now getting 

```python
/home/ubuntu/parquetRead/fastparquet/fastparquet/api.py in to_pandas(self, columns, categories, filters, index, timestamp96)
    340         index = self._get_index(index)
    341         df, views = self.pre_allocate(size, columns, categories, index,
--> 342                                       timestamp96=timestamp96)
    343         start = 0
    344         if self.file_scheme == 'simple':

/home/ubuntu/parquetRead/fastparquet/fastparquet/api.py in pre_allocate(self, size, columns, categories, index, timestamp96)
    366             categories = self.categories
    367         return _pre_allocate(size, columns, categories, index, self.cats,
--> 368                              self._dtypes(categories), timestamp96=timestamp96)
    369
    370     @property

/home/ubuntu/parquetRead/fastparquet/fastparquet/api.py in _pre_allocate(size, columns, categories, index, cs, dt, timestamp96)
    459     dtypes.extend(['category'] * len(cs))
    460     df, views = dataframe.empty(dtypes, size, cols=cols, index_name=index,
--> 461                                 index_type=index_type, cats=cats)
    462     return df, views
    463

/home/ubuntu/parquetRead/fastparquet/fastparquet/dataframe.pyc in empty(types, size, cats, cols, index_type, index_name)
     53             else:  # explicit labels list
     54                 df[str(col)] = Categorical([], categories=cats[col],
---> 55                                            fastpath=True)
     56         else:
     57             df[str(col)] = np.empty(0, dtype=t)

/home/ubuntu/.virtualenvs/parquetRead/local/lib/python2.7/site-packages/pandas/core/categorical.pyc in __init__(self, values, categories, ordered, fastpath)
    243             self._codes = coerce_indexer_dtype(values, categories)
    244             self._categories = self._validate_categories(
--> 245                 categories, fastpath=isinstance(categories, ABCIndexClass))
    246             self._ordered = ordered
    247             return

/home/ubuntu/.virtualenvs/parquetRead/local/lib/python2.7/site-packages/pandas/core/categorical.pyc in _validate_categories(cls, categories, fastpath)
    551             # Categories cannot contain NaN.
    552             if categories.hasnans:
--> 553                 raise ValueError('Categorial categories cannot be null')
    554
    555             # Categories must be unique.

ValueError: Categorial categories cannot be null
> /home/ubuntu/.virtualenvs/parquetRead/local/lib/python2.7/site-packages/pandas/core/categorical.py(553)_validate_categories()
    551             # Categories cannot contain NaN.
    552             if categories.hasnans:
--> 553                 raise ValueError('Categorial categories cannot be null')
    554
    555             # Categories must be unique.
```

When I extract the categories from ParquetFile.cats, there are no null / nan values (in fact, I dropped these in the PySpark job that created the file.

When I move to a parquet dataset that just uses the first letter of the symbol as the partition key, everything reads fine.

Trying to reproduce this and the  -, +, !, %, * errors I was getting before in a test case.  Hang tight.

**Comment by canada4663** [comment]
Alright - not 100% clean yet, but you can see a few of these other ascii / utf8 characters are breaking things as well:

```python

import os

import numpy as np
import pandas as pd
import pytest

from fastparquet.util import tempdir
from fastparquet import write, ParquetFile
import datetime as dt
import string

TEST_DATA = "test-data"

def frame_symbol_dtTrade_type_strike(days=1 * 252,
                       start_date=dt.datetime(2005, 1, 1, hour=0, minute=0, second=0),
                       symbols=['SPY', 'FB', 'TLT'],
                       numbercolumns=3):
    base = start_date
    date_list = [base + dt.timedelta(days=x) for x in range(0, days)]
    tuple_list = []
    for x in symbols:
        for y in date_list:
            for z in ['P', 'C']:
                for strike in range(100, 300, 1):
                    tuple_list.append((x, y.year, y, z, strike))
    index = pd.MultiIndex.from_tuples(tuple_list, names=('symbol', 'year', 'dtTrade', 'type', 'strike'))
    np.random.seed(seed=0)
    df = pd.DataFrame(np.random.randn(index.size, numbercolumns), 
                      index=index, columns=[x for x in string.ascii_uppercase[0:numbercolumns]])
    return df

@pytest.mark.parametrize('tempdir,input_symbols,input_days,file_scheme,input_columns,partitions,filters', 
                   [
                   (tempdir, ['NOW', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
                   (tempdir, ['NOW', 'SPY', 'VIX'], 2*252, 'simple', 2,['symbol', 'year'], [('symbol', '==', 'SPY')]),  
                   (tempdir, ['VIX*', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
                   (tempdir, ['QQQ*', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
                   (tempdir, ['QQQ!', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
                   (tempdir, ['Q%QQ', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
                   ]
                )
def test_frame_write_read_verify(tempdir, input_symbols, input_days, file_scheme, 
						    input_columns, partitions, filters):
    input_df = frame_symbol_dtTrade_type_strike(days=input_days,
												symbols=input_symbols,
												numbercolumns=input_columns)
    input_df.reset_index(inplace=True)
    fname = os.path.join(tempdir().next(), 'test')
    write(fname, input_df, partition_on=partitions, file_scheme=file_scheme, compression='SNAPPY')
    output_df = ParquetFile(fname).to_pandas()
    for col in output_df.columns:
        assert col in input_df.columns.values
    assert len(output_df) == len(output_df)
    filtered_output_df = ParquetFile(fname).to_pandas(filters=filters)
    #TODO: formatting is locked to value of type string only at present
    filters_expression = " and ".join(["{} {} '{}'".format(name, operator, value)
                                     for name, operator, value in filters])
    print input_df.columns
    print filters_expression
    filtered_input_df = input_df.query(filters_expression)
    for col in filtered_output_df.columns:
        assert col in filtered_input_df.columns.values
    assert len(filtered_output_df) == len(filtered_output_df)
```

I have traced this back to ```fastparquet.api.__init__``` which is calling ```val_to_num()``` during its execution of ```self._read_partions()``` - ```ast.literal_eval(x)``` is throwing the exception.

Full listing below

```python
    @pytest.mark.parametrize('tempdir,input_symbols,input_days,file_scheme,input_columns,partitions,filters',                                                                                          [1/28605]
                       [
                       (tempdir, ['NOW', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]),
                       (tempdir, ['NOW', 'SPY', 'VIX'], 2*252, 'simple', 2,['symbol', 'year'], [('symbol', '==', 'SPY')]),
                       (tempdir, ['VIX*', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]),
                       (tempdir, ['QQQ*', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]),
                       (tempdir, ['QQQ!', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]),
                       (tempdir, ['Q%QQ', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]),
                       ]
                    )
    def test_frame_write_read_verify(tempdir, input_symbols, input_days, file_scheme,
                                                    input_columns, partitions, filters):
        input_df = frame_symbol_dtTrade_type_strike(days=input_days,
                                                                                                symbols=input_symbols,
                                                                                                numbercolumns=input_columns)
        input_df.reset_index(inplace=True)
        fname = os.path.join(tempdir().next(), 'test')
        write(fname, input_df, partition_on=partitions, file_scheme=file_scheme, compression='SNAPPY')
>       output_df = ParquetFile(fname).to_pandas()

test/test_special_partitions_roundtrip.py:51:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
api.py:61: in __init__
    self._parse_header(f, verify)
api.py:95: in _parse_header
    self._set_attrs()
api.py:111: in _set_attrs
    self._read_partitions()
api.py:143: in _read_partitions
    for key, v in cats.items()])
util.py:49: in val_to_num
    return ast.literal_eval(x)
/usr/lib/python2.7/ast.py:49: in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

source = 'VIX*', filename = '<unknown>', mode = 'eval'

    def parse(source, filename='<unknown>', mode='exec'):
        """
        Parse the source into an AST node.
        Equivalent to compile(source, filename, mode, PyCF_ONLY_AST).
        """
>       return compile(source, filename, mode, PyCF_ONLY_AST)
E         File "<unknown>", line 1
E           VIX*
E              ^
E       SyntaxError: unexpected EOF while parsing

/usr/lib/python2.7/ast.py:37: SyntaxError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[28] > /usr/lib/python2.7/ast.py(37)parse()
-> return compile(source, filename, mode, PyCF_ONLY_AST)
```

Your proposed fix solves the problem of val_to_num being called from the filtering (read) portion, but not from the _read_partitions() function.

The error above shows error with '*' character, which might be easy to ignore, but the same error occurs with any python operand (+,-,%,!,**, etc).

I don't have a solution cooked up in my head yet - but thought I'd share the findings recreated in a way you can recreate them with a unit test to recreate.  Sorry if I missed anything obvious here and my unit test is incorrectly creating!!

**Comment by martindurant** [comment]
You test is good, if a bit verbose :)
The latest commit passes everything (at least on py35).

**Comment by canada4663** [comment]
Sorry about verbosity!  I'm a hack.

Could probably shrink the size of the test data frame to speed up tests too if needed.  I just pulled it from another test where I needed large file size.

I will test this ASAP. Thanks for the help!

**Comment by canada4663** [comment]
Sorry this took me till today.  Works well!!  I added a few additional test cases in the pytest.parametrize to ensure handling for both string and object Timestamp.   I also made the test dataframe smaller so this would run faster and added some tempdir cleanup to ensure we aren't filling up the temp directories.

New test file is below:

```python

import os
import shutil
import pytest
import numpy as np
import pandas as pd
from pandas.tslib import Timestamp
from fastparquet.util import tempdir
from fastparquet import write, ParquetFile
import datetime as dt
import string

def frame_symbol_dtTrade_type_strike(days=1 * 252,
                       start_date=dt.datetime(2005, 1, 1, hour=0, minute=0, second=0),
                       symbols=['SPY', 'FB', 'TLT'],
                       numbercolumns=1):
    base = start_date
    date_list = [base + dt.timedelta(days=x) for x in range(0, days)]
    tuple_list = []
    for x in symbols:
        for y in date_list:
            tuple_list.append((x, y.year, y))
    index = pd.MultiIndex.from_tuples(tuple_list, names=('symbol', 'year', 'dtTrade'))
    np.random.seed(seed=0)
    df = pd.DataFrame(np.random.randn(index.size, numbercolumns), 
                      index=index, columns=[x for x in string.ascii_uppercase[0:numbercolumns]])
    return df

@pytest.mark.parametrize('tempdir,input_symbols,input_days,file_scheme,input_columns,partitions,filters', 
           [
           (tempdir, ['NOW', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
           (tempdir, ['now', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
           (tempdir, ['TODAY', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
           (tempdir, ['VIX*', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
           (tempdir, ['QQQ*', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
           (tempdir, ['QQQ!', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
           (tempdir, ['Q%QQ', 'SPY', 'VIX'], 2*252, 'hive', 2, ['symbol', 'year'], [('symbol', '==', 'SPY')]), 
           (tempdir, ['NOW', 'SPY', 'VIX'], 10, 'hive', 2, ['symbol', 'dtTrade'], [('symbol', '==', 'SPY')]), 
           (tempdir, ['NOW', 'SPY', 'VIX'], 10, 'hive', 2, ['symbol', 'dtTrade'],
                                                           [('dtTrade','==','2005-01-02T00:00:00.000000000')]), 
           (tempdir, ['NOW', 'SPY', 'VIX'], 10, 'hive', 2, ['symbol', 'dtTrade'],
                                                           [('dtTrade','==', Timestamp('2005-01-01 00:00:00'))]), 
           ]
        )
def test_frame_write_read_verify(tempdir, input_symbols, input_days, file_scheme, 
						    input_columns, partitions, filters):
    #Generate Temp Director for parquet Files
    fdir = tempdir().next()
    fname = os.path.join(fdir, 'test')

    #Generate Test Input Frame
    input_df = frame_symbol_dtTrade_type_strike(days=input_days,
												symbols=input_symbols,
												numbercolumns=input_columns)
    input_df.reset_index(inplace=True)
    write(fname, input_df, partition_on=partitions, file_scheme=file_scheme, compression='SNAPPY')

    #Read Back Whole Parquet Structure
    output_df = ParquetFile(fname).to_pandas()
    for col in output_df.columns:
        assert col in input_df.columns.values
    assert len(input_df) == len(output_df)

    #Read with filters
    filtered_output_df = ParquetFile(fname).to_pandas(filters=filters)

    #Filter Input Frame to Match What Should Be Expected from parquet read
    # Handle either string or non-string inputs / works for timestamps
    filterStrings = []
    for name, operator, value in filters:
        if isinstance(value, str):
            value = "'{}'".format(value)
        else:
            value = value.__repr__()
        filterStrings.append("{} {} {}".format(name, operator, value))
    filters_expression = " and ".join(filterStrings)
    filtered_input_df = input_df.query(filters_expression)

    # Check to Ensure Columns Match
    for col in filtered_output_df.columns:
        assert col in filtered_input_df.columns.values
    # Check to Ensure Number of Rows Match
    assert len(filtered_input_df) == len(filtered_output_df)

    # Clean Up
    shutil.rmtree(fdir, ignore_errors=True)
```

**Comment by canada4663** [comment]
Added test file in commit to your fork of this in martindurant/fastparquet:fix_NOW

**Comment by martindurant** [comment]
Thank you @canada4663 for you hard work!

**Comment by canada4663** [comment]
my pleasure - thanks for making the underlying tweaks to make this work!

**Pull request merged**
