### PR TITLE
Handle rows split across 2 pages in the case of a map

### PR DESCRIPTION
**Pull request by cmenguy**
I found an issue after adding #368 - still in the case of maps, if a row is split across 2 neighboring pages, this would lead to some data loss or an exception being thrown. Exception would look something like:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/fastparquet/api.py", line 429, in to_pandas
        index=index, assign=parts)
      File "/usr/local/lib/python2.7/site-packages/fastparquet/api.py", line 260, in read_row_group
        scheme=self.file_scheme)
      File "/usr/local/lib/python2.7/site-packages/fastparquet/core.py", line 350, in read_row_group
        cats, selfmade, assign=assign)
      File "/usr/local/lib/python2.7/site-packages/fastparquet/core.py", line 327, in read_row_group_arrays
        catdef=out.get(name+'-catdef', None))
      File "/usr/local/lib/python2.7/site-packages/fastparquet/core.py", line 258, in read_col
        null, null_val, max_defi, row_idx)
      File "/usr/local/lib/python2.7/site-packages/fastparquet/encoding.py", line 296, in _assemble_objects
        assign[i] = None if have_null else part
    IndexError: index 2428 is out of bounds for axis 0 with size 2428

There are actually 2 cases to consider when you look at the implementation of `encoding._assemble_objects`:

* If the row is split between 2 pages, but this is not the last row
* If the row is split between 2 pages, and this is the last row

This fix should handle both cases, and I added a new test file which exhibits both behaviors (the last page has just 1 element which is a continuation of the last row of the previous page)

Please review @martindurant and let me know if you see anything off. I actually encountered this issue while processing my own data, and was able to process the complete dataset after this fix.

### CODE REVIEW

**Comment by martindurant** [comment]
How did you produce data showing this structure? Was this spark? It seems like somewhat of an abuse of the parquet structure... but if it exists in the wild, then I suppose we are required to handle it.

**Comment by martindurant** [comment]
Also note, that `_assemble_objects` is *slow*, and accelerating it would make a big difference for data like this. It ought to be readily cythonizable.

**Comment by cmenguy** [comment]
@martindurant Yes, this was produced through Spark 2.3.1. I actually didn't go out of my way to produce it, it just happened to be one of the files in my dataset, so I think it may happen reasonably frequently in the wild.

And agree with Cython, maybe I can look at it later as well, but this sounds like a separate task more akin to perf optimization, compared to this which seems more of a bug fix. Unless these changes would impact performance significantly (specifically the `extend` part, but I'm not sure how much of an impact it would be)

**Comment by martindurant** [comment]
> this sounds like a separate task

Totally - but it sounds like you're likely one of the first to be hit by such poor performance.

**Comment by martindurant** [comment]
OK, merging this now - your strategy looks reasonable, and the test demonstrates it. I hope spark doesn't come up with any new behaviours that we need to cover with special cases! Some of these functions are already rather long and complex.

**Pull request merged**
