### PR TITLE
String stat encoding

### LINKED ISSUE #150: string data type does not work in Amazon Athena but identical Drill file does work
Creating a little file like this:

    import fastparquet
    import pandas as pd
    df = pd.DataFrame({'z': [u'#',]})
    fastparquet.write('fastparquet.pq', df, object_encoding='utf8', compression='GZIP')

Causes Athena string comparisons to fail:

    athena "select * from my_database.fastparquet where z='#';"
    z
    -
    
(NO ROWS ARE RETURNED)

To make it work, you have to cast the column to varchar:

    athena "select * from my_database.fastparquet where CAST(z as varchar) = '#' ;"
    z
    -
    #

But creating the identical file using Drill allows you to do string literal comparisons without any casting:

    athena "select * from my_database.other_source where z='#';"
    z
    -
    #

I've attached a file with all the steps, including an octal dump of each of the two tiny parquet files.
[fastparquet_vs_drill.txt](https://github.com/dask/fastparquet/files/1002242/fastparquet_vs_drill.txt)

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #150 (I hope!)

### CODE REVIEW

**Comment by SmritikaS** [comment]
Hi, I have used the latest version of FastParquet library to write a parquet file, but querying the same on Athena gives me empty values for string datatype. (In the sample, the column sensor_id, returns empty value for all rows)

This is how I am writing the file:

    from fastparquet import write
    write(parquet_file, dataframe)

Please see the sample data in file created as below:

[
    {
        "sample_times": 1489041411.561,
        "phase_a_real": 100,
        "phase_a_reactive": 0,
        "phase_a_voltage": 0,
        "phase_a_exported_energy": 0,
        "phase_a_imported_energy": 0,
        "phase_a_wideband_reactive": 0,
        "phase_b_real": 100,
        "phase_b_reactive": 0,
        "phase_b_voltage": 0,
        "phase_b_exported_energy": 0,
        "phase_b_imported_energy": 0,
        "phase_b_wideband_reactive": 0,
        "net_reactive": 0,
        "net_voltage": 0,
        "net_exported_energy": 0,
        "net_imported_energy": 0,
        "net_wideband_reactive": 0,
        "consumption_real": 200,
        "consumption_reactive": 0,
        "consumption_voltage": 0,
        "consumption_exported_energy": 0,
        "consumption_imported_energy": 0,
        "consumption_wideband_reactive": 0,
        "generation_reactive": 0,
        "generation_voltage": 0,
        "generation_exported_energy": 0,
        "generation_imported_energy": 0,
        "generation_wideband_reactive": 0,
        "generation": 100,
        "net": 100,
        "sensor_id": "0000200000000001x0"
    },
    {
        "sample_times": 1489041411.572,
        "phase_a_real": 100,
        "phase_a_reactive": 0,
        "phase_a_voltage": 0,
        "phase_a_exported_energy": 0,
        "phase_a_imported_energy": 0,
        "phase_a_wideband_reactive": 0,
        "phase_b_real": 100,
        "phase_b_reactive": 0,
        "phase_b_voltage": 0,
        "phase_b_exported_energy": 0,
        "phase_b_imported_energy": 0,
        "phase_b_wideband_reactive": 0,
        "net_reactive": 0,
        "net_voltage": 0,
        "net_exported_energy": 0,
        "net_imported_energy": 0,
        "net_wideband_reactive": 0,
        "consumption_real": 200,
        "consumption_reactive": 0,
        "consumption_voltage": 0,
        "consumption_exported_energy": 0,
        "consumption_imported_energy": 0,
        "consumption_wideband_reactive": 0,
        "generation_reactive": 0,
        "generation_voltage": 0,
        "generation_exported_energy": 0,
        "generation_imported_energy": 0,
        "generation_wideband_reactive": 0,
        "generation": 100,
        "net": 100,
        "sensor_id": "0000200000000001x0"
    }
]

I believe this is the same issue addressed #150 
Please advise.

**Comment by martindurant** [comment]
Does the data load back OK with fastparquet (i.e., did they actually get written to the file?)? You could try encoding the field in various ways, such as string->bytes. Which reminds me, is this python 3?

**Comment by SmritikaS** [comment]
Yes, this is python3.6
Yes, the data gets written into the file, and I am able to view the same on the AWS S3 object, which is what I have copied above as sample data.

**Comment by martindurant** [comment]
> I am able to view the same on the AWS S3 object

You mean fastparquet can load it from S3, or are you viewing it with some other tool?

I'm afraid athena is beyond my knowledge, but if other frameworks such as spark can read the output, then I would suggest the fault is with athena...

**Comment by SmritikaS** [comment]
> You mean fastparquet can load it from S3, or are you viewing it with some other tool?

I am able to upload the parquet_file created using FastParquet onto an S3 bucket, when I can view the data on file, which shows that the string column is populated. (I have copied this data for reference, and shows that they are written into the file correctly).

I will try a different encoding for the specified column as you have suggested.

**Comment by martindurant** [comment]
Out of curiosity, what tool does this "viewing" of the remote data file? I assume this is some other AWS service, perhaps built into the S3 browser?

**Comment by SmritikaS** [comment]
> Out of curiosity, what tool does this "viewing" of the remote data file? I assume this is some other AWS service, perhaps built into the S3 browser?

Yes, that is correct, there is a S3 service "Select From" which basically selects the object content based on specified data format. [Select](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectSELECTContent.html)

**Comment by martindurant** [comment]
Interesting: so one of Amazon's tools can read the data correctly, but the other cannot!

**Comment by SmritikaS** [comment]
yes, the tool Select simply shows file content, while in Athena there is some mapping to convert it into a SQL table. Let me try the encoding, as well as some row format specifications on Athena and get back to you. Thanks for your quick response!

**Comment by SmritikaS** [comment]
Hi,
Just wanted to update here, that I am able to view the data correctly in Athena now.
Files were written perfectly, and viewed correctly on S3 as well, as mentioned earlier.
What was missing on my part, in Athena, I had to create table with partition and then add the partitioned data by the partition key.
Thanks again for your support :)

**Comment by martindurant** [comment]
Glad to hear it!

**Pull request merged**
