### PR TITLE
Deep digging for multi-indexes

### PR DESCRIPTION
**Pull request by martindurant**
Fixes https://github.com/dask/fastparquet/issues/349
Fixes https://github.com/pandas-dev/pandas/issues/21949
Supersedes #353 

Note that this really should be applied only to data that was pandas-born, where we can guarantee that the index columns were sensible on the way in. Currently produces a warning if the column in question was not originally categorical.
However, for categorical columns, you don't actually get a categorical index, because in the multi-index case it is pointless (you already have label encoding). Thus, you don't *quite* round-trip, but I think this is good enough.

### CODE REVIEW

**Comment by martindurant** [comment]
@0x0L , thoughts?

**Comment by 0x0L** [comment]
'brittle' may be a bit mild :) it's broken when you have multiple row groups

**Comment by martindurant** [comment]
It is not broken for multiple row-groups, if those row-groups are parts of the same original data; and if they were written independently (by Dask), then no-one should be calling `to_pandas()` on the whole dataset afterwards.

**Comment by martindurant** [comment]
But yes, @0x0L , if you have a test and have a fix in mind, would be happy to see it.

**Comment by martindurant** [comment]
You mean `pandas.api.types.union_categoricals`?

**Comment by 0x0L** [comment]
For large files columns will be chunked. Consider

```python
import pandas as pd
lrange = lambda *x: list(range(*x))
df = pd.DataFrame({'A': lrange(100), 'B': lrange(100, 0, -1), 'C': 'dummy'}).set_index(['A', 'B'])
df.head()
```

and

```python
df.to_parquet('toto.parquet', engine='fastparquet', row_group_offsets=10)
pd.read_parquet('toto.parquet', engine='fastparquet').head()
```

That's because we only see a subset of all the levels in each row group

We can fix this by merging in the categories in `_set_categories` (who should then rather be called `_add_categories`) as they arrived. But that would still leave the index in an invalid state as the levels won't be sorted.

**Comment by martindurant** [comment]
It does work if both indexes are categorical type.
Which raises the question, should the multi-index be limited to categoricals? The storage of non-categoricals *is* categorical anyway, so perhaps the safe round-trip is to make multi-indexes into  categorical columns at write time (we use `reset_index()` anyway), and refuse to load multi-indexes which are not categorical.

**Comment by 0x0L** [comment]
I'm not sure I understand you correctly: the storage of non-categorical index *is not* categorical since we use reset_index

Is the the addition of a finalizer method like in #353 incompatible with dask altogether ?

**Comment by martindurant** [comment]
I mean, that the structure of multi-indexes is inherently categorical, so that instead of calling reset_index, we should extract the codes and categories from the levels and labels, and make a categorical column  for each.

No, the finaliser is not great from a dask point of view, and it still has the original problem of not really allocating space ahead of time, which is the whole point of `dataframe.empty()`. I don't see it as a great improvement on simply erroring/ignoring the attempt to auto-set a multi-index, and require the user to call it themselves if they wish.

**Comment by 0x0L** [comment]
That's not how pyarrow does it and it will add extra-metadata (possibly large) and if the user set index=False he'll get the wrong type, etc...

**Comment by martindurant** [comment]
> will add extra-metadata (possibly large)

where, why?

My point is, that the type of each of the multi-index components is actually categorical in how it is stored, whatever pandas may have to say

**Comment by 0x0L** [comment]
For a large unique index that would mean storing the whole column in the category definitions and having an additional int column. I don't know if a thrift PLAIN_DICTIONARY can handle 1M+ entries.

Otherwise, your approach is certainly the most efficient way to directly store/read multi-indices a la pandas. That would leave the following issues

1. the categorical nature of categoricals is lost after a read. pyarrow has the same issue [i don't get why since it looks like they're calling `MultiIndex.from_array`]

2. fastparquet read with index=False will see non-cats indexes as categoricals 

3. any other parquet reader will do the same

To solve 1 and 2, there's no other way than adding metadata telling which column is a true categorical.
3 might be a real issue for some users

**Pull request merged**
