### PR TITLE
store/use partition column metadata for categorical parsing

### LINKED ISSUE #528: Hive partitions coerced to unwanted type
`val_to_num` gets called when parsing hive paths to categoricals here: https://github.com/dask/fastparquet/blob/0402257560e20b961a517ee6d770e0995e944163/fastparquet/api.py#L596 I just want the column to be returned as a string type. There doesn't appear a way to override this behavior. 

**Example**
```
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({'date': ['2020-10-01']*5 + ['2020-10-02']*5,
                   'foo': list(range(10))})
ddf = dd.from_pandas(df, npartitions=1)
ppath = 'dask_test.parquet'
ddf.to_parquet(ppath, partition_on=['date'])
df2 = dd.read_parquet(ppath).compute() #.to_dict('records')
df2.date.cat.categories[0]
# Timestamp('2020-10-01 00:00:00')
```

An override argument could be offered or maybe the parquet metadata could store the dtype.

### PR DESCRIPTION
**Pull request by postelrich**
Resolves #528 by storing partition column metadata to the pandas_metadata. On read it uses this when parsing categorical values.

### CODE REVIEW

**Comment by martindurant** [comment]
Please see failures with run where pandas==1.1.4

**Comment by martindurant** [comment]
Sorry,  I also caused some conflicts for you here.
Some of the failures I think may have been fixed in master in the meantime.

**Comment by postelrich** [comment]
@martindurant pushed fixes for the tests, don't see the ci kicking off though.

**Comment by postelrich** [comment]
@martindurant seems to have failed only for the alternate-zstd job. pandas version seems to be the same between the two py37 runs. Will take a look

**Pull request closed without merging**
