### PR TITLE
Reversing order in overwrite: 1st add new data, 2nd remove old overlapping one.

### PR DESCRIPTION
**Pull request by yohplala**
Some rework in `overwrite` and in `ParquetFile.remove_row_groups`:

- as requested in #733 , reversed order of operations when overwriting.
   - 1st, append new data and sort row groups,
   - 2nd remove old overlapping row groups and optionally sort part names

- renamed `update` into `overwrite` which is what it does.
I had some plan to work on an `update` feature with this function (which is why I initially named it `update`), but I am dropping the idea after some work on this topic in [oups](https://github.com/yohplala/oups). I can see that what is 'feasible' requires some constraints on the dataframe format, making it a function not very suited for fastparquet (that, as I picture it, targets the broadest scope possible).

- integrated in `ParquetFile.remove_row_groups` the option to sort part names after row group removal. This is something I also noticed would make sense in oups. And now that we remove row groups as a last action, it is at this time that part files have to be re-orded if requested by the user.

- following the inversion, I had to reword one test case in `test_overwrite` that test sorting of part files. I analyzed it, and this appears normal. The assertion that was failing was testing the list of part files, without re-ordering.
When part files are named, new ids start from the max id from existing part files.
  - Let say we are writing 1st 4 part files, then writing 2 new ones. The new ids are then 5 and 6. We are then removing 2. This is the new status.
  - Before, we were removing files 1st, and most notably we were removing the last one. So max id was 3 instead of remaining 4. When adding 2 new ones, their ids are 4 and 5. This was the prior status.

Closes: #733

### CODE REVIEW

**Comment by yohplala** [comment]
All 'wheels' tests + dask are failing, but this does not seem related.

Tests 'wheels':
```python
FAILED fastparquet-src/test/test_read.py::test_file_csv[test-data/gzip-nation.impala.parquet]
FAILED fastparquet-src/test/test_read.py::test_file_csv[test-data/nation.dict.parquet]
FAILED fastparquet-src/test/test_read.py::test_file_csv[test-data/nation.impala.parquet]
FAILED fastparquet-src/test/test_read.py::test_file_csv[test-data/nation.plain.parquet]
FAILED fastparquet-src/test/test_read.py::test_file_csv[test-data/snappy-nation.impala.parquet]
```
Tests 'dask':
```python
FAILED dask/dask/dataframe/io/tests/test_parquet.py::test_roundtrip[fastparquet-df12-write_kwargs12-read_kwargs12]
FAILED dask/dask/dataframe/io/tests/test_parquet.py::test_roundtrip[fastparquet-df13-write_kwargs13-read_kwargs13]
FAILED dask/dask/dataframe/io/tests/test_parquet.py::test_timestamp96 - Value...
```

**Comment by martindurant** [comment]
The most recent tests on 263df0a 7 days ago were still passing!

**Comment by yohplala** [comment]
> The most recent tests on [263df0a](https://github.com/dask/fastparquet/commit/263df0aac519f94554a8ec869711015f3bb0f358) 7 days ago were still passing!

Yes, I have not investigated. You can see the same tests are failing with PR #735 while you can see the change is clearly not involved in these errors.

**Comment by martindurant** [comment]
please merge from main

**Comment by yohplala** [comment]
> please merge from main

ok, done !

**Pull request merged**
