### PR TITLE
Be more defensive about inplace decompression in V2

### LINKED ISSUE #889: to_pandas(): cramjam.DecompressionError: snappy: output buffer (size = 262144) is smaller than required (size = 1048576)
**Describe the issue**:

Getting the following exception when trying to read a large Parquet file written with `PyArrow`:

```
Traceback (most recent call last):
  File "/Users/moo/code/ts/fastparquet-bugsies/fastparquet-decompression-error.py", line 23, in <module>
    df2 = pf2.to_pandas()
          ^^^^^^^^^^^^^^^
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/api.py", line 784, in to_pandas
    self.read_row_group_file(rg, columns, categories, index,
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/api.py", line 386, in read_row_group_file
    core.read_row_group(
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 632, in read_row_group
    read_row_group_arrays(file, rg, columns, categories, schema_helper,
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 602, in read_row_group_arrays
    read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 497, in read_col
    num += read_data_page_v2(infile, schema_helper, se, ph.data_page_header_v2, cmd,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 290, in read_data_page_v2
    decomp(np.frombuffer(infile.read(size), dtype="uint8"),
cramjam.DecompressionError: snappy: output buffer (size = 262144) is smaller than required (size = 1048576)
```

PyArrow reads the file fine.

**Minimal Complete Verifiable Example**:

[Find reproduction repo here](https://github.com/tradingstrategy-ai/fastparquet-reproduction).

500MB test file is distributed with Git LFS.

```python
from pyarrow import parquet as pq  # pyarrow 10
from fastparquet import ParquetFile  # fastparquet  2023.1.0

path = "./lending-reserves-all.parquet"

# PyArrow works
df1 = pq.read_table(path).to_pandas()

pf2 = ParquetFile(path)

# Will bomb out
#           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 290, in read_data_page_v2
#    decomp(np.frombuffer(infile.read(size), dtype="uint8"),
# cramjam.DecompressionError: snappy: output buffer (size = 262144) is smaller than required (size = 1048576)

df2 = pf2.to_pandas()

```

**Environment**:

```
fastparquet     2023.8.0     Python support for Parquet file format
```

- Python version: Python 3.11.5
- Operating System: macOS
- Install method: Poetry

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #889

### CODE REVIEW

**Comment by martindurant** [comment]
cc @miohtama

**Comment by miohtama** [comment]
I can confirm the fix works.

Unrelated, as I was working on it, I also timed both PyArrow and FastParquet read methods:

```python
from pyarrow import parquet as pq  
from fastparquet import ParquetFile  

path = "./lending-reserves-all.parquet"

start = time.time()
df1 = pq.read_table(path).to_pandas()
print("PyArrow is", time.time() - start)

start = time.time()
pf2 = ParquetFile(path)
df2 = pf2.to_pandas()
print("FastParquet is", time.time() - start)

```
PyArrow is 6.349822044372559
FastParquet is 12.303039073944092
```

**Comment by martindurant** [comment]
For decimals, fastparquet currently converts to float and this probably accounts for the time difference. After conversion, float operations will usually be faster. [my attempt](https://github.com/intake/pandas-decimal) at implementing decimals natively was even faster than anything that pyarrow can do, but due to lack of interest, I didn't implement direct fastparquet->decimal reading.

**Comment by miohtama** [comment]
@martindurant Thank you for the feedback.

Note that the difference is not that huge and likely depends on the data.

**Pull request merged**
