### PR TITLE
`ParquetFile.remove_row_groups()`

### PR DESCRIPTION
**Pull request by yohplala**
Hi, this PR proposes the implementation of a `ParquetFile.remove_row_groups()` method, as introduced in ticket #676.
The target, from this utility, is then to be able to implement 'easily' macro functions for updating a Parquet dataset.

This PR actually provides 2 new methods:

- [x] `ParquetFile._write_common_metadata()`: code
- [x] `ParquetFile._write_common_metadata()`: test case
- [x] `ParquetFile.remove_row_groups()`: code
- [x] `ParquetFile.remove_row_groups()`: test cases

Thanks in advance for your help!
PS: this PR is built on top of PR #688 (code cleaning)

### CODE REVIEW

**Comment by yohplala** [comment]
Details regarding functions / constants having been moved: from where to where.

- `ParquetException` moved from `util.py` to `thrift_structures.py`
- `write_common_metadata` moved from `writer.py` to `util.py`
- `consolidate_categories` moved from `writer.py` to `util.py`
- `MARKER` constant moved from `writer.py` to `util.py`

**Comment by martindurant** [comment]
If you move some definitions, please make sure that they are still available under the original names via imports.

**Comment by yohplala** [comment]
Hello @martindurant 
I consider this PR 'good to go'.
For `remove_row_groups()` there are 3 test cases:
- one for `hive` without partition
- one for `hive` + partitions
- one for `hive` + partitions + fsspec (local filesystem)

Please, can you have a review?
A lot of thanks in advance for your help!
Bests

**Comment by martindurant** [comment]
Please revert the creation of write.py and moving code out of writer.py. That will make things easier. After the PRs have all gone in, we can consider refactoring the large module.

**Comment by yohplala** [comment]
> Please revert the creation of write.py and moving code out of writer.py.

I am sorry @martindurant , this may show some weaknesses in my coding skills, but I don't know how to prevent ciruclar import if I revert the creation of `write.py`.

In current codebase, `writer.py`:
- contains `write_common_metadata()`
- contains calls to `write_common_metadata()` in `write()` most notably
- import `api`

In this PR, `ParquetFile._write_common_metadata()` calls `write_common_metadata()`.

So, if `write_common_metadata()` remains in `writer.py`,
- I need to import this function from `writer.py` in `api.py`.
- `writer.py` already imports `api.py`

I tried first to import specifically  `write_common_metadata()` in `api.py` but got the error message about circular import.
I may have done something wrong. Is this possible to make such an import without having this error.

All other functions in `write.py` are then in this file because at some point, there are needed by `write_common_metadata()`.


This leads me to this reversed proposal:
- should I first make a PR with only the creation of `write.py`, touching absolutely nothing in functions that are moved, opnly making copy past, and you can check visually with meld that nothing has changed.
- then we manage this PR
?

Would this be ok?

**Pull request closed without merging**
