### PR TITLE
Implement Datapage V2 writing

### PR DESCRIPTION
**Pull request by martindurant**
### datapage V2

Results in near 2x read improvement for float and timestamp without compression; no observable effect on other branches.

Needs roundtrip tests versus spark, to ensure we are generating reasonable output.

### Don't necessarily load partitioning columns

If the data is hive/drill/etc partitioned, and the user selects columns, don't include the extra implied columns unless they are listed. Note that `pf.info` and `pf.dtypes` explicitly list both normal and partitioning columns

### Row-level filtering

Implemented for to_pandas() and count(). Now supports pyarrow's syntax for AND and OR,
[[(contition1), (condition2)], (condition3)] -> (condition1 AND condition2) OR condition3

May work for read_row_group[_file], which would be needed for dask integration.

Not speedy compared to reading the data and filtering with pandas, but more memory-efficient. Optimizations still possible.

### CODE REVIEW

**Comment by yohplala** [comment]
> ### Row-level filtering
> Implemented so far for `.count` and to get the masks, but not yet during the real read.

Hi @martindurant,
If you get this feature implemented, do you think that this behavior can be controlled, i.e. either to have row-level filtering or to have row-group-level filtering?
For some cases,  I see some interests in fetching the full row group, even if some rows do ot comply with the filter.
Actually, I am starting to think to an 'overwrite v2' for which it would be useful.
If it is not possible no worries, 'overwrite v2' is far to be here yet :)

**Comment by martindurant** [comment]
Absolutely, row_filtering will be optional and off by default for now. See the provisional API for `.count()` in this PR.

**Comment by yohplala** [comment]
> Absolutely, row_filtering will be optional and off by default for now. See the provisional API for `.count()` in this PR.

Yes, sorry, it is quite clear indeed :). I should have had a look before asking.
Thanks @martindurant !

**Comment by martindurant** [comment]
@rjzamora - row-filtering is here. I may need your help making good tests and integrating with Dask. As the API sits, passing `row_filter=filters` to `ParquetFile.read_row_group_file` ought to work, but is not yet tested.

**Comment by martindurant** [comment]
(the combination of row-filtering with datapage2 is not yet implemented)

**Pull request merged**
