### PR TITLE
Remove row groups

### PR DESCRIPTION
**Pull request by martindurant**
Replaces #689

### CODE REVIEW

**Comment by yohplala** [comment]
> @yohplala : this version is almost wholly the extra method and tests for it.

Wohou, you learned me a trick here, thanks!
image

**Comment by martindurant** [comment]
If you are happy with what is here, please close your PR. I haven't yet looked in very close detail at `remove_row_groups()`, but probably this can be merged as it stands.

**Comment by yohplala** [comment]
> If you are happy with what is here, please close your PR.

Done, thanks a lot for your help, I appreciate it very much! Thanks!

**Comment by martindurant** [comment]
I removed the pruning of empty directories, I don't think we should do that.

**Comment by yohplala** [comment]
> I removed the pruning of empty directories, I don't think we should do that.

I am not sure I am explaining it correctly but 'somehow':

Partition directories are part of the DataFrame.
If by using `remove_row_groups`, a value (category) is not existing any longer, but the directory is kept (hence empty), do we consider that the Dataframe got corrupted 'somehow'?
This is how I feel it, and why I added those lines.

How does `fastparquet.ParquetFile()` behave when giving it a folder that contains empty folders?
If it is ok, then why not.

To me, it would seem that the job of removing row groups is 'somehow' not properly done.
What is possibly disturbing you in the code I wrote is that the pruning is independent of removal that has actually been conducted: it checks all sub-folders.
Maybe the implementation should focus only on partitions for which row group have been removed:
- keeping track of partition values for which row groups have been removed.
- then only checking specifically these directories, and not all the directories as I have implemented
?

Would this be more suitable? (I feel it would be better)

**Comment by yohplala** [comment]
Would it be better if the pruning of empty directories was managed in `default_remove` (as a kind of 'upward recursivity') that you implemented in `util.py`?
(at least, we would keep the simplification on the parameter ` default_remove`  you have made)

**Comment by martindurant** [comment]
Empty directories, or directories containing anything other than parquet files (.parq, .parquet) will be ignored and no change anything when loading - as confirmed by the tests. This is true for other parquet frameworks too.

**Comment by martindurant** [comment]
There is a critical flaw here: if a file contains more than one row group, the whole file will be deleted and the dataset will be corrupted. Such datasets are not made by fastparquet normally (except by successively writing "simple" files into a directory) but other frameworks do.

**Comment by yohplala** [comment]
> There is a critical flaw here: if a file contains more than one row group, the whole file will be deleted and the dataset will be corrupted. Such datasets are not made by fastparquet normally (except by successively writing "simple" files into a directory) but other frameworks do.

Martin, I created a PR directly to your own branch to solve this critical flaw.
Please, do not hesitate to ask for correction if this proposal is not ok.
https://github.com/martindurant/fastparquet/pull/5

**Comment by martindurant** [comment]
(pandas failure is due to change in pyarrow, unrelated to anything here)

**Comment by martindurant** [comment]
@yohplala , can you please verify that this merge version does everything you need it to. If yes, it's ready to go in.

**Comment by yohplala** [comment]
> @yohplala , can you please verify that this merge version does everything you need it to. If yes, it's ready to go in.

@martindurant yes I will by tomorrow evening.
Please, can you share your feedback on my reviews?
https://github.com/dask/fastparquet/pull/701/files
 - import of `partial` but not used in util.py and api.py?
 - the try/except IOError pass being present in both api.py/remove_row_groups and util.py/default_remove()
(for my own information :))

**Comment by martindurant** [comment]
> the try/except IOError pass being present in both api.py/remove_row_groups and util.py/default_remove()

The latter may be redundant, but it makes for a better standalone function. The former is required, because we might be calling another function that can raise.

**Comment by yohplala** [comment]
> @yohplala , can you please verify that this merge version does everything you need it to. If yes, it's ready to go in.

Hi @martindurant 
I pushed to your repository some last minor modifications:
- one unused import that was not existing before this PR
- a last optim for file removal in `remove_row_groups()`
Everything else is fine for me, ready for a merge
Thanks a lot for your strong support on this, much appreciated!

**Comment by yohplala** [comment]
@martindurant 

In config __Test wheels / Test wheel (numpy~=1.20.0 + ubuntu-20.04)__ `test_multi` located in `test_pi.py` is failing with error message:
```python
=========================== short test summary info ============================
FAILED fastparquet-src/test/test_api.py::test_multi - KeyError: 'a'
= 1 failed, 291 passed, 25 skipped, 1 xpassed, 2868 warnings in 147.89s (0:02:27) =
Error: Process completed with exit code 1.
```
This is not the 1st time I see this.
I saw this once, for my previous PR regarding 'code_cleaning' (PR #688).
At this time, when I pushed the PR to official repository, I had removed a seemingly unused import in `util.py`: `import os.path`.
I saw then `test_multi` failing with the same error message.
Not knowing what was wrong exactly, I add the import back, and all tests were ok again.

This time, I made the same kind of modificaiton in the dummy PR #708: I have added back in `util.py` the seemingly useless import `import shutil` that has only been added for our work on `remove_row_groups`. And again, it solves the failing test case `test_multi`.

I am a bit at a loss here. Do you know what could be the reason for `test_multi` to be so sensitive to what seem useless import (I mean, other test configs work)

For this PR #701, I am pushing to you to your own repository yet a new PR for adding it back.
Sorry for the multiple PRs.

**Comment by martindurant** [comment]
More likely it's random chance/race condition: perhaps you get the error when there are no values of "a" in the string column. I can't immediately calculate how often that situation should arise. It might be reasonable to replace the `random.choice` with something quasi-random but always the same for each run.

**Comment by yohplala** [comment]
> More likely it's random chance/race condition: perhaps you get the error when there are no values of "a" in the string column. I can't immediately calculate how often that situation should arise. It might be reasonable to replace the `random.choice` with something quasi-random but always the same for each run.

Ok, I am not sure this follows really your proposal, but I investigated on numpy website, and here is what they say about np.random.choice and np.random.randint.

Screenshot from 2021-11-17 21-37-59

Screenshot from 2021-11-17 21-38-43

So this is what I've done (while removing `import shutil`) and it seems to work (you can check with dummy PR #708.
This is also the PR to your own repo.
https://github.com/martindurant/fastparquet/pull/7

It seems to me you can now merge.
I am opening a ticket to keep track of making this update to the other test case using `choice` and `randint` and trying maybe to remove `import os.path` in `util.py`.

**Comment by martindurant** [comment]
(don't worry about the pandas failure, not our problem)

Finally in, @yohplala

**Comment by yohplala** [comment]
> Finally in, @yohplala

Thanks a lot, I am proud of our work! :)
I will restart from this state to add `append_as_row_groups` from PR #699 .
I ought to be able to do that this week-end.
Thanks again!

**Pull request merged**
