### PR TITLE
Only strip _metadata from end of file path

### LINKED ISSUE #429: Fast parquet strips `_metadata` from anywhere in path during S3 read
Not sure if an S3 only bug or not but the following code: 
```python
path = f"dataeng-data-test/testing/data/products/sku_metadata/*.parquet"
s3 = s3fs.S3FileSystem()
fs = s3fs.core.S3FileSystem()
all_paths_from_s3 = fs.glob(path=path)
 	 
custom_open = s3.open
fp_obj = fp.ParquetFile(all_paths_from_s3, open_with=custom_open)
actual = fp_obj.to_pandas()
```
results in the following error:
```sh
FileNotFoundError: dataeng-data-test/testing/data/products/sku/<partitions>/<filename>.parquet
```

Note the path descrepancy in the directory called `sku_metadata`

### PR DESCRIPTION
**Pull request by jperkelens**
Resolves #429

### CODE REVIEW

**Comment by martindurant** [comment]
This looks about right.
Would you mind making a test with a single parquet file in a tmpdir, of name "{tmpdir}/dir_metadata/file.parq"?

**Comment by jperkelens** [comment]
@martindurant yup no sweat

**Comment by jperkelens** [comment]
@martindurant I just copied the `empty.parquet` file into a nested directory in the `test-data` folder. I think this should cover your request.

**Comment by martindurant** [comment]
All good, thank you!

**Pull request merged**
