### PR TITLE
Single partition fix

### LINKED ISSUE #182: Issue while reading parquet files from s3 having single root partition & multiple leaf partitions
The root partitions information gets omitted in the absence of _metadata file in s3 & when the list of paths has only one root partition.
I am using the following code to read form s3:
```
    s3 = s3fs.S3FileSystem()
    myopen = s3.open
    fp_obj = fp.ParquetFile(s3_path_list,open_with=myopen)
    df = fp_obj.to_pandas()
```
if the list of paths (s3_path_list variable) had the following two file paths :

```
root_dir_in_s3/my_table/unique_id=500/my_date=2017-03-16/p‌​‌​a‌​rt.0.parquet 
root_dir_in_s3/my_table/unique_id=600/my_date=2017-03-25/p‌​‌​a‌​rt.1.parquet 
```
I will get  both the unique_id & my_date column information in the df.

But if the root partition ie unique_id had only one value , ie our file list path is like the following :
```
root_dir_in_s3/my_table/unique_id=500/my_date=2017-03-16/p‌​‌​a‌​rt.0.parquet 
root_dir_in_s3/my_table/unique_id=500/my_date=2017-03-25/p‌​‌​a‌​rt.1.parquet
``` 
fastparquet omits the root partition information (unique_id in our case) from the final dataframe.

Spark handles this pretty well, without _metadata file.

I believe the above scenario is a bug,

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #182

### CODE REVIEW

**Comment by martindurant** [comment]
@yackoa , can you test against your s3 data, please? You would do

    pf = fastparquet.ParquetFile(files, root='root_dir_in_s3/my_table')

**Comment by yackoa** [comment]
@martindurant would this work for multiple leaf partitions as well ?
eg:
```
root_dir_in_s3/my_table/unique_id=500/my_date=2017-03-16/p‌​‌​a‌​rt.0.parquet
root_dir_in_s3/my_table/unique_id=500/my_date=2017-03-25/p‌​‌​a‌​rt.1.parquet
root_dir_in_s3/my_table/unique_id=700/my_date=2017-02-12/p‌​‌​a‌​rt.1.parquet
```

**Comment by martindurant** [comment]
Yes indeed it should - it skips the inference of the root of the data-set in favour of the value provided.

**Comment by yackoa** [comment]
which means 
`pf = fastparquet.ParquetFile(files, root='root_dir_in_s3/my_table')`
should address if my_table had one partition or multiple partitions right ?? 💃

**Comment by martindurant** [comment]
Yes, that is the idea.

**Comment by yackoa** [comment]
awesome !!!
could you please let me know the conda forge command for the old version incase I need to revert .

I reckon the `conda install -c conda-forge fastparquet` will install the latest version with the fix.
Please correct me if I am wrong

The reason is that I have some programs working with the previous version (worked around with using `fp.assign()` with hard-coded partition assignments ) , so would need to revert incase there are any issues. It would help me very much, if you could share the conda command for the previous version as well

is it `conda install -c conda-forge fastparquet=0.1.0` ??

**Comment by martindurant** [comment]
Yes, you are correct for how to revert. This fix is not in conda-forge yet.
In fact, it is not even in master - I was hoping you might try it before I merged the fix.
I just tried now, and it works for me, so I'll merge, and try to get a version on conda-forge soon (perhaps later today).

**Comment by yackoa** [comment]
I have been using conda for testing this on my work related EC2 machine where everything. It would be easy for me to test this in my work environment, since everything is already setup. That's why I had asked for the conda vesrion.

I can  PIP install in my local if needed. but would need sometime to get my dependencies in order, since currently my local and work machine is out of sync.

**Pull request merged**
