### PR TITLE
Define `__copy__` on thrift structures

### PR DESCRIPTION
**Pull request by jcrist**
For pickle, serializing as bytes is faster, but for copy it's faster to
just copy the dictionaries and create a new object.

### CODE REVIEW

**Comment by martindurant** [comment]
Should this be the time to replace some copy operations and removing some mutations? The only use of thrift_structures.thrift copy I immediately see is in util.metadata_from_many.

**Comment by jcrist** [comment]
I've removed `thrift_copy`. I'd prefer to fix the mutations in a later PR. I plan to refactor the metadata handling into smaller functions, and manually recompose the structures rather than relying on copying - this should makes the file composition easier to see and reason about.

**Comment by martindurant** [comment]
@jcrist , all done here?
I'm happy to merge.

**Comment by jcrist** [comment]
Thanks for the review @martindurant.

**Pull request merged**
