### PR TITLE
Cython speedups for utf8 and variable length byte arrays

### PR DESCRIPTION
**Pull request by pitrou**
Before:
```
bytes: read, fixed: 6 54.659
bytes: read, fixed: None 548.77
bytes: write, fixed: 6 130.661
bytes: write, fixed: None 507.314
utf8: read, fixed: 6 466.556
utf8: read, fixed: None 948.561
utf8: write, fixed: 6 464.908
utf8: write, fixed: None 777.69
```
After:
```
bytes: read, fixed: 6 55.002
bytes: read, fixed: None 79.554
bytes: write, fixed: 6 123.404
bytes: write, fixed: None 142.213
utf8: read, fixed: 6 162.496
utf8: read, fixed: None 175.973
utf8: write, fixed: 6 209.835
utf8: write, fixed: None 191.901
```

### CODE REVIEW

**Comment by mrocklin** [comment]
The speed improvements here are really encouraging.  @pitrou can you share the benchmark you were using?  I'd like to get a rough estimate of bandwidth here.

FYI I haven't heard much from @martindurant lately.  I suspect that he is rightfully enjoying the holidays.

**Comment by mrocklin** [comment]
Ah, the benchmark is probably https://github.com/dask/fastparquet/commit/3faf36d2ead21ef3c1145383784f8a5b196e5694 (was reading over the previous issue and found this comment)

**Comment by pitrou** [comment]
Yes, it's that benchmark.

**Comment by pitrou** [comment]
The "bandwidth" would be between 5 and 10 million rows / sec. on utf8 data (the numbers are in milliseconds for a million rows). This should mostly be the overhead of creating intermediate objects, since the individual strings in that benchmark are tiny.

**Comment by mrocklin** [comment]
So it looks like we can read/write one million utf8 encoded strings of lengths uniformly in {2, 3, 6} at about 20 MB/s and for bytes at around 100 MB/s.  These numbers are very rough obviously since we don't know how this behaves with text length and such, but still serves as a decent intuitive number.

**Comment by mrocklin** [comment]
Ah, looks like we collided a bit there.  FWIW the lengths in that benchmark are somewhat typical in the applications I've seen.

**Comment by martindurant** [comment]
This looks good to me! Any reason to wait before merging?

**Comment by pitrou** [comment]
We were waiting for your review, I suppose :-) That said, I'd like to add some unittests for the specific functions before merging.

**Comment by pitrou** [comment]
Unit tests added. I've also added guards against out-of-bounds array accesses (in case of invalid input).

**Pull request merged**
