### PR TITLE
Evaluate ParquetFile dtypes and store

### LINKED ISSUE #60: Performance question on ParquetFile.dtypes
This is the result of calling `dd.read_parquet(...)`

```
         5617237 function calls (5394398 primitive calls) in 7.391 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   534360    4.412    0.000    4.412    0.000 api.py:331(<listcomp>)
      366    0.711    0.002    5.134    0.014 api.py:321(dtypes)
   442323    0.304    0.000    0.535    0.000 __init__.py:10(readall)
 181873/5    0.288    0.000    2.037    0.407 compact.py:274(read_val)
  28126/1    0.227    0.000    2.037    2.037 compact.py:247(read_struct)
   168004    0.173    0.000    0.592    0.000 compact.py:163(read_field_begin)
   126008    0.159    0.000    0.496    0.000 compact.py:69(read_varint)
   442323    0.133    0.000    0.668    0.000 __init__.py:31(read)
```

Most of the time is spent in `def dtypes(self)`

```python
    @property
    def dtypes(self):
        """ Implied types of the columns in the schema """
        dtype = {f.name: converted_types.typemap(f)
                 for f in self.schema if f.num_children is None}
        for col, dt in dtype.copy().items():
            if dt.kind == 'i':
                # int columns that may have nulls become float columns
                num_nulls = 0
                for rg in self.row_groups:
                    chunks = [c for c in rg.columns  # <<--- This is the main culprit
                              if c.meta_data.path_in_schema[-1] == col]
                    for chunk in chunks:
                        if chunk.meta_data.statistics is None:
                            num_nulls = True
                            break
                        if chunk.meta_data.statistics.null_count is None:
                            num_nulls = True
                            break
                        num_nulls += chunk.meta_data.statistics.null_count
                if num_nulls:
                    dtype[col] = np.dtype('f%i' % max(dt.itemsize, 2))
        for cat in self.cats:
            dtype[cat] = "category"
        return dtype
```

Can we reduce this cost somehow?  Is this value immutable?  Can we cache it?

### PR DESCRIPTION
**Pull request by martindurant**
Instead of having as a property and evaluating every time

Fixed #60

### CODE REVIEW

**Comment by mrocklin** [comment]
This significantly reduces the cost of what I was doing before from about 4.5 to about 2.2 seconds.

```python
In [1]: import dask.dataframe as dd
In [2]: %prun df = dd.read_parquet('indexed-full/')
```

```
Here is a current profile:

         5082765 function calls (4859926 primitive calls) in 2.486 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   442323    0.330    0.000    0.589    0.000 __init__.py:10(readall)
 181873/5    0.318    0.000    2.224    0.445 compact.py:274(read_val)
  28126/1    0.248    0.000    2.224    2.224 compact.py:247(read_struct)
   168004    0.187    0.000    0.640    0.000 compact.py:163(read_field_begin)
   126008    0.173    0.000    0.544    0.000 compact.py:69(read_varint)
   442323    0.143    0.000    0.732    0.000 __init__.py:31(read)
   442323    0.134    0.000    0.203    0.000 thrift_filetransport.py:18(_read)
   196111    0.131    0.000    0.492    0.000 compact.py:217(read_ubyte)
   442324    0.069    0.000    0.069    0.000 {method 'read' of '_io.BufferedReader' objects}
    97880    0.059    0.000    0.557    0.000 compact.py:221(read_int)
888181/888146    0.056    0.000    0.056    0.000 {built-in method builtins.len}
   167985    0.039    0.000    0.039    0.000 compact.py:133(_get_ttype)
    27761    0.036    0.000    0.196    0.000 compact.py:229(read_string)
   140150    0.033    0.000    0.033    0.000 {built-in method builtins.setattr}
   196842    0.031    0.000    0.031    0.000 {built-in method _struct.unpack}
    97880    0.029    0.000    0.029    0.000 compact.py:48(from_zig_zag)
    28649    0.026    0.000    0.026    0.000 {method 'decode' of 'bytes' object:
```

**Comment by mrocklin** [comment]
Much of this is opening the ParquetFile

```python
In [1]: import fastparquet

In [2]: %prun pf = fastparquet.ParquetFile('indexed-full')
```

```
         4834633 function calls (4624625 primitive calls) in 2.218 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   442323    0.324    0.000    0.569    0.000 __init__.py:10(readall)
 181873/5    0.301    0.000    2.198    0.440 compact.py:274(read_val)
  28126/1    0.251    0.000    2.198    2.198 compact.py:247(read_struct)
   168004    0.195    0.000    0.639    0.000 compact.py:163(read_field_begin)
   126008    0.175    0.000    0.538    0.000 compact.py:69(read_varint)
   442323    0.145    0.000    0.713    0.000 __init__.py:31(read)
   196111    0.129    0.000    0.483    0.000 compact.py:217(read_ubyte)
   442323    0.126    0.000    0.193    0.000 thrift_filetransport.py:18(_read)
   442324    0.068    0.000    0.068    0.000 {method 'read' of '_io.BufferedReader' objects}
    97880    0.060    0.000    0.553    0.000 compact.py:221(read_int)
884695/884692    0.052    0.000    0.052    0.000 {built-in method builtins.len}
   167985    0.038    0.000    0.038    0.000 compact.py:133(_get_ttype)
    27761    0.037    0.000    0.192    0.000 compact.py:229(read_string)
   139878    0.033    0.000    0.033    0.000 {built-in method builtins.setattr}
   196112    0.031    0.000    0.031    0.000 {built-in method _struct.unpack}
    97880    0.029    0.000    0.029    0.000 compact.py:48(from_zig_zag)
    27761    0.025    0.000    0.025    0.000 {method 'decode' of 'bytes' objects}
    28107    0.023    0.000    0.101    0.000 compact.py:202(read_collection_begin)
    28126    0.020    0.000    0.020    0.000 {built-in method builtins.locals}
    28127    0.020    0.000    0.020    0.000 {method 'copy' of 'dict' objects}
   218459    0.016    0.000    0.016    0.000 {built-in method builtins.ord}
   139878    0.016    0.000    0.016    0.000 compact.py:183(read_field_end)
    28126    0.014    0.000    0.017    0.000 compact.py:186(read_struct_begin)
    28128    0.013    0.000    0.087    0.000 compact.py:136(_read_size)
    28126    0.013    0.000    0.017    0.000 compact.py:190(read_struct_end)
     1460    0.011    0.000    0.011    0.000 api.py:331(<listcomp>)
    70174    0.010    0.000    0.010    0.000 {method 'append' of 'list' objects}
     6935    0.007    0.000    0.007    0.000 {method 'findall' of '_sre.SRE_Pattern' objects}
     6935    0.006    0.000    0.013    0.000 _compat.py:87(__init__)
    28130    0.005    0.000    0.005    0.000 {built-in method builtins.isinstance}
        1    0.005    0.005    0.016    0.016 api.py:106(_read_partitions)
        1    0.005    0.005    2.233    2.233 api.py:63(_parse_header)
    28126    0.004    0.000    0.004    0.000 {method 'pop' of 'list' objects}
    28107    0.004    0.000    0.004    0.000 compact.py:210(read_collection_end)
     6935    0.002    0.000    0.012    0.000 re.py:205(findall)
     6935    0.002    0.000    0.002    0.000 re.py:278(_compile)
        1    0.002    0.002    0.013    0.013 api.py:322(_dtypes)
     6935    0.001    0.000    0.001    0.000 {method 'add' of 'set' objects}
     6935    0.001    0.000    0.001    0.000 {method 'setdefault' of 'dict' objects}
        1    0.000    0.000    0.000    0.000 {built-in method io.open}
      366    0.000    0.000    0.000    0.000 api.py:56(<genexpr>)
        1    0.000    0.000    2.234    2.234 {built-in method builtins.exec}
        1    0.000    0.000    2.234    2.234 api.py:42(__init__)
      3/1    0.000    0.000    0.000    0.000 sre_parse.py:491(_parse)
        1    0.000    0.000    2.198    2.198 core.py:18(read_thrift)
        3    0.000    0.000    0.000    0.000 {method 'seek' of '_io.BufferedReader' objects}
```

```python
In [4]: pf.info
Out[4]: 
{'categories': [],
 'columns': ['tpep_pickup_datetime',
  'VendorID',
  'tpep_dropoff_datetime',
  'passenger_count',
  'trip_distance',
  'pickup_longitude',
  'pickup_latitude',
  'RateCodeID',
  'store_and_fwd_flag',
  'dropoff_longitude',
  'dropoff_latitude',
  'payment_type',
  'fare_amount',
  'extra',
  'mta_tax',
  'tip_amount',
  'tolls_amount',
  'improvement_surcharge',
  'total_amount'],
 'name': 'indexed-full/_metadata',
 'rows': 146112989}

In [5]: len(pf.row_groups)
Out[5]: 365
```

Unrelatedly, we might want to add more information to `info`.

**Comment by martindurant** [comment]
I suspect we can't do much more without digging into thrift. Thriftpy claims to be cython-accelerated and nearly as fast as a c implementation https://thriftpy.readthedocs.io/en/latest/#benchmarks , but if that were true, I don't think all those thrifty function calls should be showing up. It's worth investigating whether for some reason we are not using the optimized version.

**Comment by martindurant** [comment]
anaconda's thriftpy is one version step behind conda-forge's, might make a difference, since the changelog mentions performance improvements https://thriftpy.readthedocs.io/en/latest/#version-0-3-9

**Comment by mrocklin** [comment]
Good thought.  Tried it out and it didn't help much though.

**Comment by mrocklin** [comment]
Also tried building from source with the same results.

**Pull request merged**
