### PR TITLE
`ParquetFile.append_as_row_groups()`

### PR DESCRIPTION
**Pull request by yohplala**
__Implementation of `ParquetFile.append_as_row_groups()`__

This PR completes the proposal made in ticket #676.

The work done consisted in extracting from current `writer.write()` code dealing
  - with 'multi-part' format into a `write_multi()` (similar to the existing `write_simple()`)
  - with data index management (to have it fit for parquet format) into a `row_idx_to_cols()`
  - with some checks related 'append' into `ParquetFile.append_as_row_groups()`

In the end, the root work (appending or writing a new file) is achieved either by `write_multi` or `write_simple` which can now be found in `write.py`.

Both `writer.write` and `api.ParquetFile.append_as_row_groups` call `write_multi` or `write_simple`:
- `writer.write` call them directly when writing a file from scratch
- `api.ParquetFile.append_as_row_groups` call them when `append=True` (or overwrite)

For appending, `writer.write.py` calls `api.ParquetFile.append_as_row_groups`, bypassing creation of metadata (which was not the case before, but was a step uselessly done (these metadata not being used afterwards).

__Others changes:__
- I indicated in `writer.write` docstring the mention: 'Ignored if appending to an existing parquet dataset.' when related parameter is not used when appending.
- I had to move several methods from `writer.py` to `write.py` that are used by `write_simple` and `write_multi`.
- several test cases have been added in `test_api.py` to check `api.ParquetFile.append_as_row_groups`

### CODE REVIEW

**Comment by martindurant** [comment]
That's a lot of changes!
Are the previous PRs still live, or does this supersede them?

Naturally, it will take me some time to get to and go through this.

**Comment by yohplala** [comment]
@martindurant 
Restarting from your work with #701, I will re-create a new PR for `ParquetFile.append_as_row_groups()` and cancel this one, to avoid creating `write.py`.

**Comment by martindurant** [comment]
Perhaps you might want to wait a day or two until I can finally review and merge #701

**Comment by yohplala** [comment]
> Perhaps you might want to wait a day or two until I can finally review and merge #701

yes, good for me, thanks again!

**Comment by yohplala** [comment]
Superseded by PR #712

**Pull request closed without merging**
