### PR TITLE
Flatten schema to enable loading of non-repeated columns

### LINKED ISSUE #35: schema element name problem on nested elements
Trying to parse a parquet file, and it falls over on a nested element.

```
  File ".../fastparquet/schema.py", line 28, in schema_element
    return self.schema_elements_by_name[name]
KeyError: 'ids.eid'
```

When I look at the schema, the element in question believes its name to be 'eid', not 'ids.eid'.

```
(Pdb) p self.schema
...
<class 'parquet_thrift.SchemaElement'>
converted_type: None
field_id: None
name: ids
num_children: 4
precision: None
repetition_type: 1
scale: None
type: None
type_length: None
, <class 'parquet_thrift.SchemaElement'>
converted_type: 0
field_id: None
name: eid
num_children: None
precision: None
repetition_type: 1
scale: None
type: 6
type_length: None
, 
...
```
I shall try to create a test example which fails, and then provide a fix.

Question: which is the correct behaviour?

1. element name should be 'eid' in the schema and the code that is looking for 'ids.eid' is wrong; or
2. element name should be 'ids.eid' in the schema and the code that is looking for 'ids.eid' is right; or
3. something else

### PR DESCRIPTION
**Pull request by martindurant**
Something like
```
root
| - visitor: OPTIONAL
  | - ip: BYTE_ARRAY, UTF8, OPTIONAL
  | - network_id: BYTE_ARRAY, UTF8, OPTIONAL
  | - site_id: BYTE_ARRAY, UTF8, OPTIONAL
```
becomes
```
root
| - visitor: OPTIONAL
| - visitor.ip: BYTE_ARRAY, UTF8, OPTIONAL
| - visitor.network_id: BYTE_ARRAY, UTF8, OPTIONAL
| - visitor.site_id: BYTE_ARRAY, UTF8, OPTIONAL
```
Note that column 'visitor' contains no data at all, and there is no way
to tell the difference between visitor=NULL and all of the fields of
visitor being NULL.

Partially Fixes #35

### CODE REVIEW

**Comment by martindurant** [comment]
@j-bennet : the commit above should correctly get values for columns like "metadata.urls", but in the sample you sent, metadata is always NULL.

**Comment by j-bennet** [comment]
@martindurant I'll try it with some more realistic data where metadata is present. Thanks!

**Comment by martindurant** [comment]
Now the schema names that only contain other columns, none of their own data ('visitor', in the example above) will no longer appear in the columns list.
Still missing is work for loading lists/dicts that contain anything other than simple types. That's beyond what I can do in reasonable time.

**Comment by j-bennet** [comment]
I installed fastparquet from your branch and tried to load the dataframe with it. Progress: things didn't break! :) It's great. There's a few things that don't work right.

- all timestamp values turned into junk (`timestamp`, `timestamp_5min`, etc.)

https://gist.github.com/j-bennet/e036b8fd61c2e22f236a424ffacc4f52

- some null values turned into `None`, and some into `nan`, which looks kind of odd

https://gist.github.com/j-bennet/f6f5226ddb503aecc794590ed0d60116

I still didn't get around to trying this on a dataframe with metas, which is the most complex one. But I will.

**Comment by martindurant** [comment]
For timestamps, they are encoded using int96, which is not the standard for parquet. to_pandas has a keyword argument to do the conversion into timestamps, and I newly added an attribute to ParquetFile to make it easy to convert *all* such columns (which is quite likely what you want):

     pf.to_pandas(timestamp96=pf.int96cols)

**Comment by martindurant** [comment]
> some null values turned into None, and some into nan

This is expected, because of pandas' internals. None is for object columns, NaN for float columns (ints silently become floats if there are any nulls) and you can also have NaT for time columns. Pandas functions treat them the same when doing aggregations or any of the null-oriented methods (drop, fill...).

**Comment by j-bennet** [comment]
Perfect, `timestamp96=pf.int96cols` fixes the timestamp issue!

**Comment by j-bennet** [comment]
Trying this out on a dataframe with metadata. Here is one row:

```
ipdb> df.iloc[0]
url                                               http://blog.parsely.com/post/46/
_type                                                                          url
apikey                                                            blog.parsely.com
audience_segment_id                                                             11
metrics                          {u'$any/returning/engaged_seconds': 9, u'$any/...
referrers                                                                     None
ts_apikey                                                      2017-02-02 02:15:00
vis_new                                                                         []
vis_returning                               [908d02d6-df11-49a2-9a20-139e528ddb59]
visitors                                    [908d02d6-df11-49a2-9a20-139e528ddb59]
ts                                                             2017-02-02 07:15:00
_index                                                   casterisk-5min-2017.02.02
_id                              http://blog.parsely.com/post/46/|blog.parsely....
index_ts                                                2017-06-29 16:38:03.088000
freq                                                                          5min
campaign                                                                      None
metas.authors                                                    Andrew Montalenti
metas.canonical_hash                                                        QtBJro
metas.canonical_hash64                                                 FZyXxuRY9Os
metas.canonical_url                http://blog.parse.ly/post/46/whatever-it-takes/
metas.data_source                                                            crawl
metas.full_content_word_count                                                 1681
metas.image_url                  http://farm9.staticflickr.com/8051/8119717424_...
metas.page_type                                                               post
metas.post_id                      http://blog.parse.ly/post/46/whatever-it-takes/
metas.pub_date                                                 2012-11-02 04:00:00
metas.section                                                Analytics That Matter
metas.tags                                                            [None, None]
metas.thumb_url_medium           https://images.parsely.com/rr1hHDt1zufL7Gol-iN...
metas.title                                                      Whatever It Takes
metas.urls                              [None, None, None, None, None, None, None]
Name: 0, dtype: object
```

Looks like all urls became `None` in `metas.urls`, and all `metas.authors` became strings, instead of string arrays.

urls:

```
ipdb> df["metas.urls"]
0       [None, None, None, None, None, None, None]
1       [None, None, None, None, None, None, None]
2       [None, None, None, None, None, None, None]
3       [None, None, None, None, None, None, None]
4                         [None, None, None, None]
5                         [None, None, None, None]
6                         [None, None, None, None]
7                         [None, None, None, None]
8                         [None, None, None, None]
9                         [None, None, None, None]
10                        [None, None, None, None]
11                        [None, None, None, None]
12                        [None, None, None, None]
13                        [None, None, None, None]
14                        [None, None, None, None]
15                        [None, None, None, None]
16                        [None, None, None, None]
17                        [None, None, None, None]
18                        [None, None, None, None]
19                        [None, None, None, None]
20                        [None, None, None, None]
21                        [None, None, None, None]
22                        [None, None, None, None]
23                        [None, None, None, None]
24                        [None, None, None, None]
25                        [None, None, None, None]
26                        [None, None, None, None]
27                        [None, None, None, None]
28                        [None, None, None, None]
29                        [None, None, None, None]
```

authors:

```
ipdb> df["metas.authors"]
0       Andrew Montalenti
1       Andrew Montalenti
2       Andrew Montalenti
3       Andrew Montalenti
4                Parse.ly
5                Parse.ly
6                Parse.ly
7                Parse.ly
8       Andrew Montalenti
9       Andrew Montalenti
10      Andrew Montalenti
11      Andrew Montalenti
12      Andrew Montalenti
13      Andrew Montalenti
14      Andrew Montalenti
15      Andrew Montalenti
16          Allie VanNest
17          Allie VanNest
18          Allie VanNest
19          Allie VanNest
20          Allie VanNest
21          Allie VanNest
22          Allie VanNest
23          Allie VanNest
24          Allie VanNest
25          Allie VanNest
26          Allie VanNest
27          Allie VanNest
28          Allie VanNest
29          Allie VanNest
```

**Comment by j-bennet** [comment]
Here is a small sample of parquet with metas.
[part-00000-d1037e5b-9108-45ac-8413-e9237359b63e.gz.parquet.zip](https://github.com/dask/fastparquet/files/1112863/part-00000-d1037e5b-9108-45ac-8413-e9237359b63e.gz.parquet.zip)

**Comment by martindurant** [comment]
@j-bennet , here is another attempt, seems to work with your data.
Note that there is an argument that metas.authors should not be in lists, because there is only ever one value, at most, per row, and building lists is slow - however, lists are a more accurate representation of the schema structure.

**Comment by j-bennet** [comment]
@martindurant Yes, we do have data where `authors` is populated with a list.

**Comment by j-bennet** [comment]
Yes! However, if I now switch back to reading with dask.dataframe, it still breaks.

this:

```
     import dask.dataframe as dd
    df = dd.read_parquet(sample_file_path)
```

causes:

```
Traceback (most recent call last):
  File "main_dask.py", line 50, in <module>
    main()
  File "main_dask.py", line 45, in main
    df = dd.read_parquet(sample_file_path)
  File "/Users/irina/.pyenv/versions/redask/lib/python2.7/site-packages/dask/dataframe/io/parquet.py", line 286, in read_parquet
    categories=categories, index=index)
  File "/Users/irina/.pyenv/versions/redask/lib/python2.7/site-packages/dask/dataframe/io/parquet.py", line 68, in _read_fastparquet
    minmax = fastparquet.api.sorted_partitioned_columns(pf)
  File "/Users/irina/.pyenv/versions/redask/lib/python2.7/site-packages/fastparquet/api.py", line 638, in sorted_partitioned_columns
    s = statistics(pf)
  File "/Users/irina/.pyenv/versions/redask/lib/python2.7/site-packages/fastparquet/api.py", line 602, in statistics
    for n in ['min', 'max', 'null_count', 'distinct_count']}
  File "/Users/irina/.pyenv/versions/redask/lib/python2.7/site-packages/fastparquet/api.py", line 602, in <dictcomp>
    for n in ['min', 'max', 'null_count', 'distinct_count']}
  File "/Users/irina/.pyenv/versions/redask/lib/python2.7/site-packages/fastparquet/api.py", line 601, in <dictcomp>
    for col in obj.columns}
KeyError: u'metrics'
```

**Comment by martindurant** [comment]
@j-bennet , OK, I think this fixes it for the dask side too.

**Comment by j-bennet** [comment]
I get a different error now:

```
Traceback (most recent call last):
  File "main_dask.py", line 50, in <module>
    main()
  File "main_dask.py", line 45, in main
    df = dd.read_parquet(sample_file_path)
  File "/Users/irina/.pyenv/versions/redask/lib/python2.7/site-packages/dask/dataframe/io/parquet.py", line 286, in read_parquet
    categories=categories, index=index)
  File "/Users/irina/.pyenv/versions/redask/lib/python2.7/site-packages/dask/dataframe/io/parquet.py", line 82, in _read_fastparquet
    % sorted(minmax))
ValueError: Multiple possible indexes exist: [u'_id', u'_index', u'_type', u'apikey', u'audience_segment_id', u'freq', u'index_ts', u'metas.canonical_hash', u'metas.canonical_hash64', u'metas.canonical_url', u'metas.data_source', u'metas.full_content_word_count', u'metas.image_url', u'metas.page_type', u'metas.post_id', u'metas.pub_date', u'metas.section', u'metas.thumb_url_medium', u'metas.title', u'ts', u'ts_apikey', u'url'].  Please select one with index='index-name'
```

**Comment by martindurant** [comment]
That isn't an error - if you have no explicit index set in the metadata (which you won't when the data comes from spark), then you have to choose one with `index=`, which can be False if you want no index set.

**Comment by j-bennet** [comment]
@martindurant Oh I see. Thanks for the tip. Yes, I would say it's good t merge now!

**Comment by j-bennet** [comment]
🎉

**Comment by daniel-severo** [comment]
related question: https://stackoverflow.com/questions/45341182/nested-data-in-parquet-with-python

**Pull request merged**
