### PR TITLE
Enable append to an empty dataset

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by shughes-uk** [comment]
Looks like changes are required in Dask itself for this too.
```
Traceback (most recent call last):
  File "/Users/shughes/Programming/anaconda-stats/statistics_generators/parse_logs.py", line 102, in <module>
    parse_log_files(args.start_dt, args.end_dt, args.tdir, args.ddir, args.type, args.source_tag, dask_client)
  File "/Users/shughes/Programming/anaconda-stats/statistics_generators/parse_logs.py", line 73, in parse_log_files
    future = dataframes[download_type].to_parquet(dirpath, compute=False, append=True, compression='SNAPPY', write_index=True, object_encoding='utf8')
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/dataframe/core.py", line 955, in to_parquet
    return to_parquet(path, self, *args, **kwargs)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/dataframe/io/parquet.py", line 390, in to_parquet
    raise ValueError('Requested file scheme is hive, '

```

**Comment by martindurant** [comment]
Garrr, OK, I'll get back to you on that.

**Comment by shughes-uk** [comment]
There's also another error in dask itself when loading empty parquet
```
Traceback (most recent call last):
  File "/Users/shughes/Programming/anaconda-stats/util_scripts/influx_importer.py", line 270, in <module>
    main(sys.argv)
  File "/Users/shughes/Programming/anaconda-stats/util_scripts/influx_importer.py", line 266, in main
    upload(args)
  File "/Users/shughes/Programming/anaconda-stats/util_scripts/influx_importer.py", line 133, in upload
    upload_parquet(target_files, db_client, args.measurement_n, args.start_dt, args.end_dt)
  File "/Users/shughes/Programming/anaconda-stats/util_scripts/influx_importer.py", line 96, in upload_parquet
    df, f_cols, t_cols = parse_parquet(target_dirs, start_dt, end_dt)
  File "/Users/shughes/Programming/anaconda-stats/util_scripts/influx_importer.py", line 142, in parse_parquet
    df = dask.dataframe.read_parquet(directory, index='timestamp')
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/dataframe/io/parquet.py", line 287, in read_parquet
    categories=categories, index=index)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/dataframe/io/parquet.py", line 113, in _read_fastparquet
    [minmax[index_col]['max'][-1]])
IndexError: list index out of range

```

I can make an issue for it on the dask project itself if you'd like.

**Comment by martindurant** [comment]
xref https://github.com/dask/dask/pull/2443

**Pull request merged**
