### PR TITLE
Fix compression functions for `zstd` library (#381)

### LINKED ISSUE #381: ZSTD implemented wrong if `zstd` is installed
When calling `write()` with `compression='zstd'`, if you have [`zstd`](https://pypi.org/project/zstd/) installed instead of `zstandard` you get the following exception:

```
Traceback (most recent call last):
  File "./load_logs.py", line 80, in <module>
    load_files()
  File "./load_logs.py", line 77, in load_files
    compression='zstd', engine='fastparquet', has_nulls=False)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pandas/core/frame.py", line 1945, in to_parquet
    compression=compression, **kwargs)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pandas/io/parquet.py", line 257, in to_parquet
    return impl.write(df, path, compression=compression, **kwargs)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pandas/io/parquet.py", line 218, in write
    compression=compression, **kwargs)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/writer.py", line 848, in write
    compression, open_with, has_nulls, append)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/writer.py", line 717, in write_simple
    compression=compression)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/writer.py", line 614, in make_row_group
    compression=comp)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/writer.py", line 536, in write_column
    bdata = compress_data(bdata, compression)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/compression.py", line 133, in compress_data
    return compressions[algorithm.upper()](data)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/compression.py", line 94, in zstd_compress
    cctx = zstd.ZstdCompressor(**kwargs)
AttributeError: module 'zstd' has no attribute 'ZstdCompressor'
```

Using `zstd` instead of `zstandard` *is* supported in theory, but the bug appears to be a copy-paste error. The compression and decompression functions can be simplified to something like the following:

```py
def zstd_compress(data, compression_level=None):
    if compression_level is not None:
        return zstd.compress(data, compression_level)
    return zstd.compress(data)
def zstd_decompress(data):
    return zstd.decompress(data)
```

Environment:
* Python 3.7.0
* MacOS High Sierra
* Packages:

```
fastparquet==0.1.6
zstd==1.3.5.1
```

### PR DESCRIPTION
**Pull request by dargueta**
## Changes

1. Closes #381 
2. Switches primary test environment to tox, though `python setup.py test` will still work

This changes fallback code for the ZSTD compression codec to use [zstd](https://pypi.org/project/zstd/) correctly. The current code appears to be a copy-paste mistake from the `zstandard` code.

This PR will also make fastparquet compatible with [cython-zstd](https://pypi.org/project/cython-zstd/) in theory though I don't know the import name for that module. If it's also `zstd`, it'll work automatically, as the functions and arguments are identical to the aforementioned `zstd` library.

### CODE REVIEW

**Comment by martindurant** [comment]
Tests still reporting `AttributeError: module 'zstandard' has no attribute 'ZstdCompressor'`

**Comment by dargueta** [comment]
Yeah, I know. Still working on it. "WIP" in the title is "work in progress"

**Comment by martindurant** [comment]
Sorry, please take you time.

**Comment by martindurant** [comment]
Any progress here?

**Comment by dargueta** [comment]
Crap sorry I completely forgot about this

**Comment by fhertz** [comment]
Hello, 

I am also interested by this compression, it's a big gain on cloud environnent to optimize  storage costs.

Big thanks !

**Comment by dargueta** [comment]
@martindurant looks like everything's fixed except the tests are blowing up on Python 2 because a library we depend on somewhere (I think NumPy) has dropped support for Python 2, but apparently hasn't set their `python_requires` properly to exclude it.

This isn't too hard to fix but will require modifying some more code in `setup.py` that expects only one line in the requirements file to have `numpy` in it. I'll tweak it a bit more.

**Comment by dargueta** [comment]
I have no idea why `test_multi_cat_fail` is suddenly breaking only when `zstd` is installed, even though it's not the default compression algorithm.

**Comment by martindurant** [comment]
I don't personally have the time to debug right now.

**Comment by dargueta** [comment]
@martindurant updating the PR to drop Python 2 support seemed to do the trick. Tests are working now.

**Pull request merged**
