### PR TITLE
Preliminary support for Arrays and maps

### LINKED ISSUE #104: Request: Single-level structured columns
Add support for array and map-type columns, which become columns of python lists and dicts (see also #97 discussion)

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #104 

Successfully loads arrays and maps (lists and dicts) written by pyspark. Tests include allowing None entries and/or allowing None values (but a map key can never be None).
This is a *slow* algorithm. 
Whether it works for non-spark data is currently unknown.

### CODE REVIEW

**Comment by martindurant** [comment]
Additionally: complex schemas will no longer cause problems on parsing (but you still cannot load deep-nested structures), the former "helper" is now simply `ParquetFile.schema` (the raw list version persists as `ParquetFile._schema`) and prints nicely with
```
print(pf.schema)  # the pyspark-generated test data
>
- spark_schema:
| - map_op_op: MAP, OPTIONAL
|   - key_value: REPEATED
|   | - key: BYTE_ARRAY, UTF8, REQUIRED
|     - value: BYTE_ARRAY, UTF8, OPTIONAL
| - map_op_req: MAP, OPTIONAL
|   - key_value: REPEATED
|   | - key: BYTE_ARRAY, UTF8, REQUIRED
|     - value: BYTE_ARRAY, UTF8, REQUIRED
| - map_req_op: MAP, REQUIRED
|   - key_value: REPEATED
|   | - key: BYTE_ARRAY, UTF8, REQUIRED
|     - value: BYTE_ARRAY, UTF8, OPTIONAL
| - map_req_req: MAP, REQUIRED
|   - key_value: REPEATED
|   | - key: BYTE_ARRAY, UTF8, REQUIRED
|     - value: BYTE_ARRAY, UTF8, REQUIRED
| - arr_op_op: LIST, OPTIONAL
|   - list: REPEATED
|     - element: BYTE_ARRAY, UTF8, OPTIONAL
| - arr_op_req: LIST, OPTIONAL
|   - list: REPEATED
|     - element: BYTE_ARRAY, UTF8, REQUIRED
| - arr_req_op: LIST, REQUIRED
|   - list: REPEATED
|     - element: BYTE_ARRAY, UTF8, OPTIONAL
  - arr_req_req: LIST, REQUIRED
    - list: REPEATED
      - element: BYTE_ARRAY, UTF8, REQUIRED
```

**Comment by mrocklin** [comment]
FWIW I think it's also reasonable to say that doing this well short-term is
out-of-scope, and stating loudly that fastparquet only supports the Pandas
data model.  I suspect that diving into this problem may prove time
consuming.

**Comment by martindurant** [comment]
I don't aim to do this well or to handle the general case (which is much too hard). The code I have here should be readily convertible to cython, but I won't even do that unless someone complains of performance issues.

**Comment by martindurant** [comment]
Merging this in any case: the ability not to fall over on complicated schemas (where you might load just the one-level columns) and give a nice schema output is worthwhile even if the maps/lists don't get used much.

**Pull request merged**
