### PR TITLE
Fix reading timezones from metadata

### PR DESCRIPTION
**Pull request by barbuz**
Fixes https://github.com/dask/fastparquet/issues/908

Instead of always assuming that the `numpy_type` entry of the metadata for a datetime column will include a timezone, this adapts to both cases and relies only on the timezone from the `metadata.timezone` entry for that column.

### CODE REVIEW

**Comment by martindurant** [comment]
Any chance you can unapply the formatting changes, to make it easier to see what actually is new in this PR?

**Comment by martindurant** [comment]
Fail of the pandas run seems to have something to do with a new version of one or more pytest plugins?

**Comment by barbuz** [comment]
> Any chance you can unapply the formatting changes, to make it easier to see what actually is new in this PR?

Sorry about that, I didn't realise that my editor decided to reformat the whole file. I've reverted those changes now.

> Fail of the pandas run seems to have something to do with a new version of one or more pytest plugins?

I am not sure about this, could you help me figure it out now that it's easy to see what changed in the tests?

**Comment by martindurant** [comment]
The fail is fixed on main, please merge or rebase.

**Pull request merged**
