### PR TITLE
Add support for building on aarch64 on Linux

### LINKED ISSUE #770: fastparquet 0.8.1 Linux aarch64 builds are missing
**What happened**:
On a Linux aarch64 system, does not install 0.8.1 via pip. (This works fine on MacOS arm64.)

**What you expected to happen**:
fastparquet 0.8.1 to be installed

**Minimal Complete Verifiable Example**:

```
$ pip install fastparquet==0.8.1
ERROR: Could not find a version that satisfies the requirement fastparquet==0.8.1 (from versions: 0.0.1, 0.0.1.post1, 0.0.1.post2, 0.0.2, 0.0.3, 0.0.4, 0.0.4.post1, 0.0.5, 0.0.6, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.6.0, 0.6.0.post1, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.7.1, 0.7.2, 0.8.0)
ERROR: No matching distribution found for fastparquet==0.8.1
```

**Anything else we need to know?**:
.whl file is missing on pypi: https://pypi.org/project/fastparquet/0.8.1/#files

**Environment**:
Python 3.9.11
Linux 4e20d812a0b1 5.10.104-linuxkit #1 SMP PREEMPT Wed Mar 9 19:01:25 UTC 2022 aarch64 GNU/Linux
fastparquet 0.8.1

### PR DESCRIPTION
**Pull request by michael-sanders**
This adds in the appropriate option to build on aarch64 (ARM) on Linux in addition to builds generated by the 'auto' option. This is as per the docs at https://cibuildwheel.readthedocs.io/en/stable/options/#archs

Closes #770

### CODE REVIEW

**Comment by martindurant** [comment]
@michael-sanders , it seems that building all those wheels under QEMU is is just taking too long with this addition. Do you think we can split up the job, building some wheels in each, to get around this? As it stands, you can include "wheels" as the commit message to try the build.

**Comment by martindurant** [comment]
built all manylinux, timed out building muslinux. Do we need both, can they be split?

**Comment by michael-sanders** [comment]
> built all manylinux, timed out building muslinux. Do we need both, can they be split?

Thanks @martindurant. I'll take a look.

**Comment by michael-sanders** [comment]
The `numpy` dependency does not yet supply musllinux wheels and so we have to build them. This takes too long on aarch64 and so musllinux wheels should be disabled for this platform (see https://github.com/dask/fastparquet/pull/771/commits/fe96260ba9983eb4145604a41ae15d2ac6776e64).  We can re-enable this when `numpy` has merged a fix for https://github.com/numpy/numpy/issues/20089

**Comment by martindurant** [comment]
aarch wheels are up.

**Comment by michael-sanders** [comment]
Great, thanks 👍

**Pull request merged**
