### PR TITLE
Index import

### LINKED ISSUE #470: Importing from pandas.core.index is deprecated
The imports here (and maybe in other places as well):

https://github.com/dask/fastparquet/blob/8767c2f94975aed8d052a9d0ad6f5e4e630a6f12/fastparquet/dataframe.py#L5

is deprecated now in pandas master (and it has also been private before). Those imports are simply available from the top-level namespace, so no need to import them from there.

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes #470.

### CODE REVIEW

**Comment by martindurant** [comment]
Damn you, pandas internal API :)

**Comment by TomAugspurger** [comment]
Just wait for all of `pandas.core` to be officially deprecated :)

**Comment by Dr-Irv** [comment]
@TomAugspurger Don't you have to delete this line:  
```
from pandas.core.index import CategoricalIndex, RangeIndex, Index, MultiIndex
```

**Comment by TomAugspurger** [comment]
Good catch! Fixed, and added a test.

**Pull request merged**
