### PR TITLE
Add parameter 'n_prev_rows' to 'to_pandas()' in case 'row_filter=True'

### PR DESCRIPTION
**Pull request by yohplala**
Hi,
This PR answers ticket #665: retrieving n preceding rows when applying filters.
I hope the integration of this feature can be considered.
Have a good evening,
Bests,

### CODE REVIEW

**Comment by yohplala** [comment]
Hi, please, is there any feedback regarding this PR proposal?
I can modify if there is any adjustments to be done.
Thanks in advance, bests,

**Comment by yohplala** [comment]
Hello, I am very sorry, I don't mean to bother.
Please may I help / should I change something in the PR so that it can be merged?
If this PR's scope is not acceptable, please, don't hesitate to say so.
I don't see other more 'relevant / elegant' alternative to this at the moment, but if you point out what may be a trouble in proposed implementation, I can try to derive a new one taking this into account.
Thanks a lot for any feedbacks,
Have a good day,
Bests

**Comment by martindurant** [comment]
My feeling is, that this rather complicates the code to add a feature and yet-another-kwarg that will be very rarely used by anyone but yourself. Since you could always get the whole data and do the filtering afterwards.

One simpler and more general version of this kind of idea might be: to allow the caller to supply their own boolean mask in `row_filter=` (instead of `True`).

**Comment by yohplala** [comment]
> My feeling is, that this rather complicates the code to add a feature and yet-another-kwarg that will be very rarely used by anyone but yourself. Since you could always get the whole data and do the filtering afterwards.
> 
> One simpler and more general version of this kind of idea might be: to allow the caller to supply their own boolean mask in `row_filter=` (instead of `True`).

Thanks for the feedback @martindurant.
This few lines modify actually 2 variables, `sel` and `rgs`. Actually, `sel` is valid for a `rgs` (this is the point of having these lines here, to manage the case when previous rows are lying in the preceding row group).

So, yes, I can change the PR as you propose, instead `row_filter` would accept a tuple `(sel, rgs)`.
I will look at it shortly,
Thanks again!

**Comment by yohplala** [comment]
Following proposal to make ` row_filter` accepting directly the list of rows to keep in end DataFrame, I am closing this PR, in favor of PR #681 .

**Pull request closed without merging**
