### PR TITLE
Integrate pytest with setup.py

### PR DESCRIPTION
**Pull request by jonathanunderwood**
This integrates pytest with setuptools to enable running of the tests with a simple `python setup.py test`

### CODE REVIEW

**Comment by martindurant** [comment]
Was this already solved in #287 ?

**Comment by jonathanunderwood** [comment]
Oh, hah! Yes, mostly. #287 doesn't add the setup.cfg bits, so although that allows `python setup.py pytest` to work, `python setup.py test` probably doesn't. If you merge #287, I'll rebase this and just add anything else extra.

**Comment by martindurant** [comment]
merged #287 
Looks like you don't need to rebase -  ok to go here?

**Comment by jonathanunderwood** [comment]
Yup, looks fine to me.

**Pull request merged**
