### PR TITLE
Fix bitpack for long runs

### LINKED ISSUE #604: fastparquet v 0.6.1 crashes on read
**What happened**:

Loading a 32Mb parquet file crashes with a core dump. It takes up 3Gb of memory before crashing.

**What you expected to happen**:

Prior to this version (unsure if 0.5.0 or 0.6.0) loading the same file worked with no problem. Tested on 0.5.0 without issues. Will test on 0.6.0 also.

**Minimal Complete Verifiable Example**:

Sorry I can't provide the file as it is private data. 

```python
pd.read_parquet(filename)
```

**Anything else we need to know?**:

This issue appeared today (2021-05-12) so we assume it is related to release 0.6.1. Switching to `pyarrow` fixed the problem immediately. Previously, `pyarrow` was not installed and `fastparquet` was always used. Our Jupyter environments are ephemeral and torn down every day, so we reinstall new versions daily for work. Thus we assume 0.6.1 introduced the bug.

**Environment**:

- Dask version: ? 0.6.1 fastparquet
- Python version: 3.8.5
- Operating System: Ubuntu 20.04.1 LTS (Focal Fossa) on AWS
- Install method (conda, pip, source): pip

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #604

@jonathanbranam , please test for your case.

### CODE REVIEW

**Comment by jonathanbranam** [comment]
Yes, I can confirm that this works. I installed from `main` and read the original file with no issues whatsoever. The read file is identical to when I read with `pyarrow`. (Although, I did notice that `pyarrow` reads some category dtypes as object whereas `fastparquet` deserializes them correctly as categories.

**Comment by martindurant** [comment]
> pyarrow reads some category dtypes as object

Fascinating! I assume in these cases, fastparuet must be much faster than arrow.

**Comment by jonathanbranam** [comment]
For this test case, I couldn't see much of a difference in read speed, but obviously the resulting DataFrame is smaller with the categories. I ran this test several times with nearly identical results. Appears that `pyarrow` is very slightly faster?
Screen Shot 2021-05-13 at 1 21 16 PM

**Comment by martindurant** [comment]
More work to do for me, in that case :)  There are many factors which determine performance.

**Pull request merged**
