### PR TITLE
Further _from_sequence

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by martindurant** [comment]
@jrbourbeau , applying the same code change elsewhere, which seems to work on pandas 1.5 too. I am mystified why changing to remove the regression on one spot made the other two spots start to fail - or maybe pandas pushed point update release to both 2x and 1.5x lines.

**Comment by jrbourbeau** [comment]
Thanks @martindurant. I just confirmed all Dask parquet tests are now passing with Python 3.10 + pandas 1.5.3 + this branch

> I am mystified why changing to remove the regression on one spot made the other two spots start to fail

I think it was always failing earlier in the callstack on line 202

**Comment by martindurant** [comment]
2023.10.1 sdist is on pypi, wheels are building and conda-forge will kick off in due course.

**Comment by jrbourbeau** [comment]
Thank you @martindurant (cc @mrocklin for visiblity)

**Pull request merged**
