### PR TITLE
Don't set _codes for upcoming pandas 2

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by martindurant** [comment]
A pyarrow upstream test in dask if failing. 
@rjzamora @jrbourbeau 

How much of a hurry to get this in and released?

**Comment by martindurant** [comment]
test_pandas_timestamp_overflow_pyarrow

**Review by jrbourbeau — COMMENTED** [review]
Thanks for the ping @martindurant. Not immediately sure what the issue is. It's also popping up in https://github.com/dask/dask/issues/9736 -- I'll take a look

**Comment by jrbourbeau** [comment]
https://github.com/dask/dask/pull/9777

**Comment by jrbourbeau** [comment]
Alright, restarting CI as that test should be fixed upstream in `dask`

**Pull request merged**
