### PR TITLE
Fixed error if a certain partition is empty, when writing a partioned…

### PR DESCRIPTION
**Pull request by andrethrill**
… parquet file

Related to #346 .

### CODE REVIEW

**Comment by andrethrill** [comment]
This is failing, will push a fix soon.

**Comment by martindurant** [comment]
Hah, so you needed a bit of both :)
Would you mind making a test with empties, perhaps exactly like the original filtered partition case?

**Comment by andrethrill** [comment]
Indeed @martindurant !

I pushed the test now. Everything should be fine now.

**Comment by martindurant** [comment]
Thanks @andrethrill

**Pull request merged**
