### PR TITLE
Trial multi-file support

### LINKED ISSUE #89: Can't read the parquet directory without _metadata file
When I am trying to open directory with parquet files it crashes when *_metadata* file is not being found:

```
(lambda2) [ec2-user@ ~]$ cat start.py
#!/usr/bin/python
from fastparquet import ParquetFile
fn = "/home/ec2-user/parquet-gzip/"
#fn = "/home/ec2-user/parquet-gzip/part-00000-test-gz.parquet"
pf = ParquetFile(fn)
df = pf.to_pandas()
print (df)
(lambda2) [ec2-user@ ~]$ ls -lah parquet-gzip/
total 21M
drwxr-xr-x  2 ec2-user ec2-user 4.0K Feb 22 13:31 .
drwx------ 14 ec2-user ec2-user 4.0K Feb 22 13:34 ..
-rw-r--r--  1 ec2-user ec2-user  11M Feb 22 12:09 part-00000-test.gz.parquet
-rw-r--r--  1 ec2-user ec2-user  11M Feb 22 12:09 part-00001-test.gz.parquet
(lambda2) [ec2-user@ ~]$ python start.py
Traceback (most recent call last):
  File "start.py", line 5, in <module>
    pf = ParquetFile(fn)
  File "/home/ec2-user/lambda2/local/lib/python2.7/dist-packages/fastparquet/api.py", line 52, in __init__
    with open_with(fn, 'rb') as f:
  File "/home/ec2-user/lambda2/local/lib/python2.7/dist-packages/fastparquet/util.py", line 39, in default_open
    return open(f, mode)
IOError: [Errno 21] Is a directory: '/home/ec2-user/parquet-gzip/'
(lambda2) [ec2-user@ ~]$
```
Output from strace:
```
3741  open("/home/ec2-user/parquet-gzip//_metadata", O_RDONLY) = -1 ENOENT (No such file or directory)
```

Would it be difficult to implement support for directories without this file? After some research I suspect they are not obligatory:

https://forums.databricks.com/questions/6494/do-you-need-a-metadata-file-in-a-parquet-folder-to.html

### PR DESCRIPTION
**Pull request by martindurant**
For the case where spark has written data without a _metadata file

Fixes #89 #90

### CODE REVIEW

**Comment by martindurant** [comment]
@mingzhou , @bluszcz : please see if this meets your requirements.

You can pass a list of files to ParquetFile. You need to generate that list yourself, e.g., by using glob.

**Comment by mingzhou** [comment]
Yeah, this is perfect. Thanks @martindurant .

**Comment by bluszcz** [comment]
Let me check.

**Comment by bluszcz** [comment]
```
In [2]: import fastparquet

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-7ca6bf5779cf> in <module>()
----> 1 import fastparquet

/Users/rafal/repo/fastparquet/fastparquet/__init__.py in <module>()
     13
     14 from .thrift_structures import parquet_thrift
---> 15 from .core import read_thrift
     16 from .writer import write
     17 from . import core, schema, converted_types, api

/Users/rafal/repo/fastparquet/fastparquet/core.py in <module>()
      8 from thriftpy.protocol.compact import TCompactProtocolFactory
      9
---> 10 from . import encoding
     11 from .compression import decompress_data
     12 from .converted_types import convert, typemap

/Users/rafal/repo/fastparquet/fastparquet/encoding.py in <module>()
     14 import sys
     15
---> 16 from .speedups import unpack_byte_array
     17 from .thrift_structures import parquet_thrift
     18 from .util import byte_buffer

ModuleNotFoundError: No module named 'fastparquet.speedups'

In [3]:
```

**Comment by martindurant** [comment]
speedups is a cython module. To install from master, you will need to point pip at the repo, or download and run `python setup.py build`. The option `install` should automatically run build for you.

**Comment by bluszcz** [comment]
Actually, I think I exactly did it - downloaded the repo from github, python setup.py install. Will check again and will let know.

**Comment by InforeCapital** [comment]
Hi, @martindurant . I finally install the master branch today. However, using glob("dir/*/*.parquet") will missing the partition info?  
can we extract partition info from the directory tree such as  `date=20170316`?
Thanks a lot!

**Comment by mingzhou** [comment]
Hi, @martindurant . I finally install the master branch today. However, using glob("dir//.parquet") will missing the partition info?
can we extract partition info from the directory tree such as date=20170316?
Thanks a lot!

**Comment by martindurant** [comment]
Yes, if you have files structures something like:
```
data/myset.parquet/date=20170316/part.0.parquet
data/myset.parquet/date=20170316/part.1.parquet
data/myset.parquet/date=20170317/part.0.parquet
data/myset.parquet/date=20170317/part.1.parquet
```

then you can do
```
files = glob.glob('data/myset.parquet/*/*.parquet')
pf = fastparquet.ParquetFiles(files)
df = pf.to_pandas()
```
You will have a field "date" in the output with the appropriate values. To apparent location of `pf` will be "data/myset.parquet/_metadata" (even though there is no such file). Note that the values of date look like (categorical) integers, and there is no way to tell the difference, so you will need to do something like `df['date'] = pd.to_datetime(out.date.astype(str))` to convert.

**Comment by mingzhou** [comment]
Hi @martindurant . After 
`df = pf.to_pandas()`
I didn't get a  `date` column in `df`.
Thanks a lot.

**Comment by martindurant** [comment]
Session looks like this for me:

```
In [1]: import pandas as pd

In [2]: import fastparquet

In [3]: df = pd.DataFrame({'a': [0,2,1]})

In [4]: import os

In [6]: os.makedirs('data/date=20170316')

In [7]: os.makedirs('data/date=20170317')

In [8]: fastparquet.write('data/date=20170316/part.0.parq', df)

In [9]: fastparquet.write('data/date=20170317/part.0.parq', df)

In [10]: import glob

In [11]: files = glob.glob('data/*/*.parq')

In [12]: pf = fastparquet.ParquetFile(files)

In [13]: pf.to_pandas()
Out[13]:
   a      date
0  0  20170316
1  2  20170316
2  1  20170316
3  0  20170317
4  2  20170317
5  1  20170317
```

**Comment by mingzhou** [comment]
hi @martindurant  I tried your code:
`
import pandas as pd
import fastparquet
df = pd.DataFrame({"a" : [0, 2, 1]})
import os
os.makedirs("data/date=20170316")
os.makedirs("data/date=20170317")
fastparquet.write('data/date=20170316/part.0.parq', df)
fastparquet.write('data/date=20170317/part.0.parq', df)
import glob
files = glob.glob('data/*/*.parq')
pf = fastparquet.ParquetFile(files)
pf.to_pandas()
`
however, get the following result:
`
pf.to_pandas()
   a
0  0
1  2
2  1
3  0
4  2
5  1
`

**Comment by martindurant** [comment]
Are you sure you have the latest master?

**Comment by InforeCapital** [comment]
Hi, Martin, I'm using this branch [master]. Thanks.




qi@infore.com
 
From: Martin Durant
Date: 2017-03-17 09:52
To: dask/fastparquet
CC: InforeCapital; Comment
Subject: Re: [dask/fastparquet] Trial multi-file support (#95)
Are you sure you have the latest master?

**Comment by mingzhou** [comment]
Hi @martindurant . I've replied your email. Thanks so much.

**Comment by martindurant** [comment]
Most puzzling that the exact same code with the exact same version of the library produces different results. 

I do notice that you are on Windows, and we are dealing with path parsing, so I can only suppose that I don't accurately account for `'/'`->`'\'`. I don't have a windows systems to test with, Perhaps in fastparquet/util.py:L192
```
s = re.compile("([a-zA-Z_]+)=([^/]+)")
->
s = re.compile("([a-zA-Z_]+)=([^\\]+)")
```
and switching the direction of all the path separators in the code above.
Would you mind doing a little experimentation?

**Comment by martindurant** [comment]
The same regex pattern also appears twice in fastparquet/api.py

**Comment by mingzhou** [comment]
Hi @martindurant 
It works! After change the regex pattern in `util.py` and `api.py` and `core.py`.

**Comment by DigitalPig** [comment]
Quick question, does this PR means we can use the same syntax in `dask`'s `read_parquet`?

```python
import dask.dataframe as dd
files = glob.glob('data/myset.parquet/*/*.parquet')
df = dd.read_parquet(files)
```

**Comment by martindurant** [comment]
I haven't tried it, but I believe it might work.

**Comment by mickdelaney** [comment]
Hi,
i've tried the latest master but am getting an error.  (i'm on windows 10)


```
files = glob.glob('.\companies.parquet\*.parquet')
pf = fastparquet.ParquetFile(files)
df = pf.to_pandas()
```
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-73edfe1bdcca> in <module>()
      1 pf = fastparquet.ParquetFile(files)
----> 2 df = pf.to_pandas()

C:\conda\envs\tensorflow\lib\site-packages\fastparquet\api.py in to_pandas(self, columns, categories, filters, index, timestamp96)
    340                          for (name, v) in views.items()}
    341                 self.read_row_group_file(rg, columns, categories, index,
--> 342                                          assign=parts, timestamp96=timestamp96)
    343                 start += rg.num_rows
    344         return df

C:\conda\envs\tensorflow\lib\site-packages\fastparquet\api.py in read_row_group_file(self, rg, columns, categories, index, assign, timestamp96)
    164                 fn, rg, columns, categories, self.schema, self.cats,
    165                 open=self.open, selfmade=self.selfmade, index=index,
--> 166                 assign=assign, timestamp96=timestamp96)
    167         if ret:
    168             return df

C:\conda\envs\tensorflow\lib\site-packages\fastparquet\core.py in read_row_group_file(fn, rg, columns, categories, schema_helper, cats, open, selfmade, index, assign, timestamp96, sep)
    281         return read_row_group(f, rg, columns, categories, schema_helper, cats,
    282                               selfmade=selfmade, index=index, assign=assign,
--> 283                               timestamp96=timestamp96, sep=sep)
    284 
    285 

C:\conda\envs\tensorflow\lib\site-packages\fastparquet\core.py in read_row_group(file, rg, columns, categories, schema_helper, cats, selfmade, index, assign, timestamp96, sep)
    333         raise RuntimeError('Going with pre-allocation!')
    334     read_row_group_arrays(file, rg, columns, categories, schema_helper,
--> 335                           cats, selfmade, assign=assign, timestamp96=timestamp96)
    336 
    337     for cat in cats:

C:\conda\envs\tensorflow\lib\site-packages\fastparquet\core.py in read_row_group_arrays(file, rg, columns, categories, schema_helper, cats, selfmade, assign, timestamp96)
    310                  selfmade=selfmade, assign=out[name],
    311                  catdef=out[name+'-catdef'] if use else None,
--> 312                  timestamp96=mr)
    313 
    314         if _is_map_like(schema_helper, column):

C:\conda\envs\tensorflow\lib\site-packages\fastparquet\core.py in read_col(column, schema_helper, infile, use_cat, grab_dict, selfmade, assign, catdef, timestamp96)
    234             skip_nulls = False
    235         defi, rep, val = read_data_page(infile, schema_helper, ph, cmd,
--> 236                                         skip_nulls, selfmade=selfmade)
    237         if rep is not None and assign.dtype.kind != 'O':  # pragma: no cover
    238             # this should never get called

C:\conda\envs\tensorflow\lib\site-packages\fastparquet\core.py in read_data_page(f, helper, header, metadata, skip_nulls, selfmade)
    104                                            dtype=np.uint8))
    105 
--> 106     repetition_levels = read_rep(io_obj, daph, helper, metadata)
    107 
    108     if skip_nulls and not helper.is_required(metadata.path_in_schema):

C:\conda\envs\tensorflow\lib\site-packages\fastparquet\core.py in read_rep(io_obj, daph, helper, metadata)
     84             metadata.path_in_schema)
     85         bit_width = encoding.width_from_max_int(max_repetition_level)
---> 86         repetition_levels = read_data(io_obj, daph.repetition_level_encoding,
     87                                       daph.num_values,
     88                                       bit_width)[:daph.num_values]

AttributeError: 'NoneType' object has no attribute 'repetition_level_encoding'
```

**Comment by martindurant** [comment]
It seems your chunk does not have a data page header. I have not come across any data like this - how was it made? Is there any chance that you can share an extract of the data which demonstrates the problem?

**Pull request merged**
