### PR TITLE
Convert windows paths at first opportunity

### PR DESCRIPTION
**Pull request by martindurant**
Then all paths written to metadata will be posix-style.

See #228 #227 

Would like some eyes on this.

@apiszcz , could you run the test suite on Windows and experiment with this in general?

### CODE REVIEW

**Comment by apiszcz** [comment]
Yes, these are ready? should i do pull to test all changes (assuming they
are ready)

**Comment by martindurant** [comment]
https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

I think it would be:

    pip install pip install git+https://github.com/martindurant/fastparquet.git@windows_path

(assuming you are in an environment with all the prerequisites already installed)

**Comment by apiszcz** [comment]
Thank you.
The pip command required --upgrade.

Hmm
  File "C:\test\lib\fastparquet\api.py", line 740, in filter_val
    if op in ['==', '>='] and val > vmax:
TypeError: unorderable types: int() > str()

**Comment by apiszcz** [comment]
We'll call this 20171006 < 6PM
works fine.

Performed pip update and
```
Traceback (most recent call last):
  File "lib\_testdm\testdm.py", line 590, in <module>
    main()
  File "lib\_testdm\testdm.py", line 581, in main
    ovdm.filter(oc,ol,ou,src,modes)
  File "lib\_testdm\testdm.py", line 322, in filter
    df = ddf.read_parquet(pfp, columns=columns, filters=fd['parquetfilter']).compute()
  File "C:\g\test\lib\dask\dataframe\io\parquet.py", line 292, in read_parquet
    categories=categories, index=index)
  File "C:\g\test\lib\dask\dataframe\io\parquet.py", line 63, in _read_fastparquet
    rgs = [rg for rg in pf.row_groups if
  File "C:\g\test\lib\dask\dataframe\io\parquet.py", line 65, in <listcomp>
    not(fastparquet.api.filter_out_cats(rg, filters, sep=fs.sep))]
  File "C:\g\test\lib\fastparquet\api.py", line 716, in filter_out_cats
    out = filter_val(op, val, v0, v0)
  File "C:\g\test\lib\fastparquet\api.py", line 740, in filter_val
    if op in ['==', '>='] and val > vmax:
TypeError: unorderable types: int() > str()

```

**Comment by martindurant** [comment]
Could you please include the line you tried, which is failing, and the path its failing for?

**Comment by apiszcz** [comment]
```
$ diff fastparquet/writer.py fastparquetnew/writer.py
534d533
<
573d571
<
783a782,784
>     if sep == '\\':
>         filename = '/'.join(filename.split('\\'))
>         sep = '/'
813,815c814,816
<             #partition_on = list(pf.cats)
<             if set(partition_on) != set(pf.cats):
<                 raise ValueError('When appending, partitioning columns must match existing data')
---
>             if tuple(partition_on) != tuple(pf.cats):
>                 raise ValueError('When appending, partitioning columns must'
>                                  ' match existing data')
976a978,980
>     if sep == '\\':
>         file_list = ['/'.join(f.split('\\')) for f in file_list]
>         sep = '/'

```

**Comment by apiszcz** [comment]
```
$ diff fastparquet/api.py fastparquetnew/api.py
82c82
<         self.sep = sep
---
>         self.sep = '/'
83a84,85
>             if sep == '\\':  # Windows path
>                 fn = ['/'.join(f.split(sep)) for f in fn]
87c89,90
<                 self.fn = sep.join([basepath, '_metadata'])  # effective file
---
>                 # effective file
>                 self.fn = self.sep.join([basepath, '_metadata'])
92a96,97
>             if sep == '\\':  # Windows path
>                 fn = '/'.join(fn.split(sep))
94c99
<                 fn2 = sep.join([fn, '_metadata'])
---
>                 fn2 = self.sep.join([fn, '_metadata'])
141c146,147
<         self.file_scheme = get_file_scheme([rg.columns[0].file_path for rg in self.row_groups], self.sep)
---
>         self.file_scheme = get_file_scheme([rg.columns[0].file_path
>                                            for rg in self.row_groups], self.sep)
165c171
<         cats = {}
---
>         cats = OrderedDict()
179c185
<                      for key, v in cats.items()])
---
>                                 for key, v in cats.items()])
276,277c282
<                 not (filter_out_cats(rg, filters, sep=self.sep))]
<                 #not(filter_out_cats(rg, filters))]
---
>                 not(filter_out_cats(rg, filters, self.sep))]
668,669c673,674
<                 sorted(max) == max and
<                 all(mx < mn for mx, mn in zip(max[:-1], min[1:]))):
---
>                     sorted(max) == max and
>                     all(mx < mn for mx, mn in zip(max[:-1], min[1:]))):
694a700
>     # TODO: fix for Drill
707d712
<
711d715
<

```

**Comment by martindurant** [comment]
What I meant was, which line were you executing on the user side, outside of the library? What paths were you trying to access?

**Comment by apiszcz** [comment]
Sorry, from the user side:

`df = ddf.read_parquet(pfp, columns=columns, filters=fd['parquetfilter']).compute()`

**Comment by martindurant** [comment]
Can you try now, please?

**Comment by apiszcz** [comment]
I tried the same pip upgrade line as yesterday, however I seem to be having
issues.
Are the latest files on github for api.py and writer.py?

**Comment by apiszcz** [comment]
PIP fails with this
Requirement already up-to-date: pip in c:\a\a3\lib\site-packages
Collecting install
  Could not find a version that satisfies the requirement install (from
versions: )
No matching distribution found for install

conda forge installed 0.1.0

**Comment by apiszcz** [comment]
I made the two changes core.py from
https://github.com/dask/fastparquet/commit/15bb148 which produce the
following stack trace

Traceback (most recent call last):
  File "lib\_testdm\testdm.py", line 664, in <module>
    main()
  File "lib\_testdm\testdm.py", line 655, in main
    ovdm.filter(oc,ol,ou,src,modes)
  File "lib\_testdm\testdm.py", line 430, in filter
    df = ddf.read_parquet(pfp, columns=columns,
filters=fd['parquetfilter']).compute()
  File "C:\g\test\lib\dask\base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\g\test\lib\dask\base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "C:\g\test\lib\dask\threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "C:\g\test\lib\dask\local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "C:\g\test\lib\dask\compatibility.py", line 60, in reraise
    raise exc
  File "C:\g\test\lib\dask\local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "C:\g\test\lib\dask\local.py", line 271, in _execute_task
    return func(*args2)
  File "C:\g\test\lib\dask\dataframe\io\parquet.py", line 143, in
_read_parquet_row_group
    open=open, assign=views)
  File "C:\g\test\lib\fastparquet\core.py", line 284, in read_row_group_file
    sep=sep, scheme=scheme)
  File "C:\g\test\lib\fastparquet\core.py", line 345, in read_row_group
    val = val_to_num([p[1] for p in partitions if p[0] == cat][0])
IndexError: list index out of range

**Comment by apiszcz** [comment]
This line installed 0.1.2 . all files are from 8/28/2017
conda install -c conda-forge fastparquet

**Comment by martindurant** [comment]
> This line installed 0.1.2 . all files are from 8/28/2017
> conda install -c conda-forge fastparquet

Yes, that is what should happen.

**Comment by apiszcz** [comment]
Ok, standing by future future releases to test.

**Comment by apiszcz** [comment]
Using pip --upgrade
pip install --upgrade git+
https://github.com/martindurant/fastparquet.git@windows_path

here is the stack trace


Traceback (most recent call last):
  File "lib\_testdm\testdm.py", line 664, in <module>
    main()
  File "lib\_testdm\testdm.py", line 655, in main
    ovdm.filter(oc,ol,ou,src,modes)
  File "lib\_testdm\testdm.py", line 430, in filter
    df = ddf.read_parquet(pfp, columns=columns,
filters=fd['parquetfilter']).compute()
  File "C:\g\test\lib\dask\dataframe\io\parquet.py", line 292, in
read_parquet
    categories=categories, index=index)
  File "C:\g\test\lib\dask\dataframe\io\parquet.py", line 63, in
_read_fastparquet
    rgs = [rg for rg in pf.row_groups if
  File "C:\g\test\lib\dask\dataframe\io\parquet.py", line 65, in <listcomp>
    not(fastparquet.api.filter_out_cats(rg, filters, sep=fs.sep))]
  File "C:\g\test\lib\fastparquet\api.py", line 716, in filter_out_cats
    out = filter_val(op, val, v0, v0)
  File "C:\g\test\lib\fastparquet\api.py", line 740, in filter_val
    if op in ['==', '>='] and val > vmax:
TypeError: unorderable types: int() > str()

**Comment by apiszcz** [comment]
Getting a build error:

```
    Compiling fastparquet/speedups.pyx because it changed.
    [1/1] Cythonizing fastparquet/speedups.pyx
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\api.py -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\compression.py -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\converted_types.py -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\core.py -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\dataframe.py -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\encoding.py -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\schema.py -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\thrift_structures.py -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\util.py -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\writer.py -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\__init__.py -> build\lib.win-amd64-3.5\fastparquet
    running egg_info
    creating fastparquet.egg-info
    writing fastparquet.egg-info\PKG-INFO
    writing requirements to fastparquet.egg-info\requires.txt
    writing dependency_links to fastparquet.egg-info\dependency_links.txt
    writing top-level names to fastparquet.egg-info\top_level.txt
    writing manifest file 'fastparquet.egg-info\SOURCES.txt'
    reading manifest file 'fastparquet.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs\_build'
    writing manifest file 'fastparquet.egg-info\SOURCES.txt'
    copying fastparquet\parquet.thrift -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\speedups.c -> build\lib.win-amd64-3.5\fastparquet
    copying fastparquet\speedups.pyx -> build\lib.win-amd64-3.5\fastparquet
    creating build\lib.win-amd64-3.5\fastparquet\benchmarks
    copying fastparquet\benchmarks\columns.py -> build\lib.win-amd64-3.5\fastparquet\benchmarks
    creating build\lib.win-amd64-3.5\fastparquet\parquet_thrift
    copying fastparquet\parquet_thrift\__init__.py -> build\lib.win-amd64-3.5\fastparquet\parquet_thrift
    creating build\lib.win-amd64-3.5\fastparquet\parquet_thrift\parquet
    copying fastparquet\parquet_thrift\parquet\__init__.py -> build\lib.win-amd64-3.5\fastparquet\parquet_thrift\parquet
    copying fastparquet\parquet_thrift\parquet\constants.py -> build\lib.win-amd64-3.5\fastparquet\parquet_thrift\parquet
    copying fastparquet\parquet_thrift\parquet\ttypes.py -> build\lib.win-amd64-3.5\fastparquet\parquet_thrift\parquet
    creating build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\__init__.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_api.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_aroundtrips.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_compression.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_converted_types.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_dataframe.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_encoding.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_output.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_partition_filters_specialstrings.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_read.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_speedups.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_thrift_structures.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_util.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\test_with_n.py -> build\lib.win-amd64-3.5\fastparquet\test
    copying fastparquet\test\util.py -> build\lib.win-amd64-3.5\fastparquet\test
    running build_ext
    building 'fastparquet.speedups' extension
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    creating build\temp.win-amd64-3.5\Release\fastparquet
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\a\a3\lib\site-packages\numpy\core\include -Ic:\a\a3\include -Ic:\a\a3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\wdf\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\wdf\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\wdf\um" "-IC:\Program Files (x86)\Windows Kits\10\include\wdf\winrt" /Tcfastparquet/speedups.c /Fobuild\temp.win-amd64-3.5\Release\fastparquet/speedups.obj
    speedups.c
    c:\a\a3\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2:\\Users\\usr\\AppData\\Local\\Temp\\pip-u7g96yuj-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\usr\AppData\Local\Temp\pip-z6fqfqs4-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\usr\AppData\Local\Temp\pip-u7g96yuj-build\evalrios.tif, band 1: Too big block : 393646 * 4096
```

**Comment by apiszcz** [comment]
I copied all file from git EXCEPT speedups which I copied from 0.1.3.

Note import from fastparquetgit



```python
import sys
import dask
from dask import dataframe as dd
import fastparquetgit as fp
import pandas as pd
import numpy as np
print('dask',dask.__version__,'fastparquet',fp.__version__)

df=pd.DataFrame(np.random.randint(0,100,(5,3)),columns=list('abc'))
fp.write('__fpdasktest.parq',df,file_scheme='hive',partition_on=['a'],compression='SNAPPY')

df2=dd.read_parquet('__fpdasktest.parq', filters=[('a','>',10)]).compute()
print(df,'\n',df2)

from dask154 import dataframe as dd
df3=dd.read_parquet('__fpdasktest.parq', filters=[('a','>',10)]).compute()
print(df3)

```

    dask 0.15.2 fastparquet 0.1.3
        a   b   c
    0  40  81  38
    1  75  14  96
    2  56  84  53
    3  44  94  49
    4  27  94  90 
         b   c   a
    0  81  38  40
    0  84  53  56
    0  14  96  75
    0  94  90  27
    0  94  49  44
    


    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-3-64445e66143b> in <module>()
         14 
         15 from dask154 import dataframe as dd
    ---> 16 df3=dd.read_parquet('__fpdasktest.parq', filters=[('a','>',10)]).compute()
         17 print(df3)
    

    C:\g\via\lib\dask154\dataframe\io\parquet.py in read_parquet(path, columns, filters, categories, index, storage_options, engine)
        291         return _read_fastparquet(fs, paths, file_opener, columns=columns,
        292                                  filters=filters,
    --> 293                                  categories=categories, index=index)
        294     else:
        295         return _read_pyarrow(fs, paths, file_opener, columns=columns,
    

    C:\g\via\lib\dask154\dataframe\io\parquet.py in _read_fastparquet(fs, paths, myopen, columns, filters, categories, index, storage_options)
         61     name = 'read-parquet-' + tokenize(pf, columns, categories)
         62 
    ---> 63     rgs = [rg for rg in pf.row_groups if
         64            not(fastparquet.api.filter_out_stats(rg, filters, pf.schema)) and
         65            not(fastparquet.api.filter_out_cats(rg, filters))]
    

    C:\g\via\lib\dask154\dataframe\io\parquet.py in <listcomp>(.0)
         63     rgs = [rg for rg in pf.row_groups if
         64            not(fastparquet.api.filter_out_stats(rg, filters, pf.schema)) and
    ---> 65            not(fastparquet.api.filter_out_cats(rg, filters))]
         66 
         67     if index is False:
    

    C:\g\via\lib\fastparquet\api.py in filter_out_cats(rg, filters, sep)
        709             else:
        710                 v0 = val_to_num(v)
    --> 711             out = filter_val(op, val, v0, v0)
        712             if out is True:
        713                 return True
    

    C:\g\via\lib\fastparquet\api.py in filter_val(op, val, vmin, vmax)
        735         if op in ['==', '>='] and val > vmax:
        736             return True
    --> 737         if op == '>' and val >= vmax:
        738             return True
        739         if op == 'in' and min(val) > vmax:
    

    TypeError: unorderable types: int() >= str()

**Comment by martindurant** [comment]
How about now, together with https://github.com/martindurant/dask/tree/win_paths
(this amounts to [one line](https://github.com/martindurant/dask/blob/win_paths/dask/dataframe/io/parquet.py#L375)).

**Comment by martindurant** [comment]
Another uncompromising attempt for you.

**Comment by apiszcz** [comment]
Works ok with DASK 0.15.2, but not the latest DASK.





```
dask 0.15.2 fastparquet 0.1.3
    a   b   c
0  79  41  15
1  68  80  83
2  32  48  57
3  95  26  86
4  16  86  66 
     b   c   a
0  86  66  16
0  48  57  32
0  26  86  95
0  80  83  68
0  41  15  79

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-5de996628a2b> in <module>()
     14 
     15 from dask154 import dataframe as dd
---> 16 df3=dd.read_parquet('__fpdasktest.parq', filters=[('a','>',10)]).compute()
     17 print(df3)

C:\g\test\lib\dask154\dataframe\io\parquet.py in read_parquet(path, columns, filters, categories, index, storage_options, engine)
    291         return _read_fastparquet(fs, paths, file_opener, columns=columns,
    292                                  filters=filters,
--> 293                                  categories=categories, index=index)
    294     else:
    295         return _read_pyarrow(fs, paths, file_opener, columns=columns,

C:\g\test\lib\dask154\dataframe\io\parquet.py in _read_fastparquet(fs, paths, myopen, columns, filters, categories, index, storage_options)
     61     name = 'read-parquet-' + tokenize(pf, columns, categories)
     62 
---> 63     rgs = [rg for rg in pf.row_groups if
     64            not(fastparquet.api.filter_out_stats(rg, filters, pf.schema)) and
     65            not(fastparquet.api.filter_out_cats(rg, filters))]

C:\g\test\lib\dask154\dataframe\io\parquet.py in <listcomp>(.0)
     63     rgs = [rg for rg in pf.row_groups if
     64            not(fastparquet.api.filter_out_stats(rg, filters, pf.schema)) and
---> 65            not(fastparquet.api.filter_out_cats(rg, filters))]
     66 
     67     if index is False:

C:\g\test\lib\fastparquet\api.py in filter_out_cats(rg, filters, sep)
    709             else:
    710                 v0 = val_to_num(v)
--> 711             out = filter_val(op, val, v0, v0)
    712             if out is True:
    713                 return True

C:\g\test\lib\fastparquet\api.py in filter_val(op, val, vmin, vmax)
    735         if op in ['==', '>='] and val > vmax:
    736             return True
--> 737         if op == '>' and val >= vmax:
    738             return True
    739         if op == 'in' and min(val) > vmax:

TypeError: unorderable types: int() >= str()
```

**Comment by apiszcz** [comment]
I am not sure I have all the latest files, the blitz update for example how do I obtain all the updates?

**Comment by apiszcz** [comment]
I updated api.py, core.py and util.py manually from the change log, (FILE View, Raw, Save As).
What may help is getting all the latest files for fastparquet assuming DASK has not changed.

Here is the latest
```





dask 0.15.2 fastparquet 0.1.3
    a   b   c
0  10  65  23
1  69  15  82
2  90  36  96
3  11  60   0
4   9  23  53 
     b   c   a
0  60   0  11
0  36  96  90
0  15  82  69

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-5de996628a2b> in <module>()
     14 
     15 from dask154 import dataframe as dd
---> 16 df3=dd.read_parquet('__fpdasktest.parq', filters=[('a','>',10)]).compute()
     17 print(df3)

C:\g\test\lib\dask154\dataframe\io\parquet.py in read_parquet(path, columns, filters, categories, index, storage_options, engine)
    291         return _read_fastparquet(fs, paths, file_opener, columns=columns,
    292                                  filters=filters,
--> 293                                  categories=categories, index=index)
    294     else:
    295         return _read_pyarrow(fs, paths, file_opener, columns=columns,

C:\g\test\lib\dask154\dataframe\io\parquet.py in _read_fastparquet(fs, paths, myopen, columns, filters, categories, index, storage_options)
     61     name = 'read-parquet-' + tokenize(pf, columns, categories)
     62 
---> 63     rgs = [rg for rg in pf.row_groups if
     64            not(fastparquet.api.filter_out_stats(rg, filters, pf.schema)) and
     65            not(fastparquet.api.filter_out_cats(rg, filters))]

C:\g\test\lib\dask154\dataframe\io\parquet.py in <listcomp>(.0)
     63     rgs = [rg for rg in pf.row_groups if
     64            not(fastparquet.api.filter_out_stats(rg, filters, pf.schema)) and
---> 65            not(fastparquet.api.filter_out_cats(rg, filters))]
     66 
     67     if index is False:

C:\g\test\lib\fastparquet\api.py in filter_out_cats(rg, filters, sep)
    709     for cat, v in pairs:
    710 
--> 711         app_filters = [f[1:] for f in filters if f[0] == cat]
    712         for op, val in app_filters:
    713             tstr = six.string_types + (six.text_type, )

C:\g\test\lib\fastparquet\api.py in filter_val(op, val, vmin, vmax)
    735     True or False
    736     """
--> 737     if (op == 'in' and vmax is not None and vmin is not None and
    738             vmax == vmin and vmax not in val):
    739         return True

TypeError: unorderable types: int() >= str()
```

**Comment by martindurant** [comment]
The line you post does not contain `>=`, so I am stumped. Furthermore, the filter had `>`.
Please ensure you are using the latest code for fastparquet and have made the suggested change in dask. Also, make sure you are writing the data afresh each time, so as not be confused by paths created by previous iterations.
Also, you should try loading with fastparquet directly, first, so we can differentiate the source of your problems.

**Comment by apiszcz** [comment]
I followed your suggestions, removing the old folder was the issue.
The latest dask works with the latest fastparquet.

```
import os, sys
import dask
from dask import dataframe as dd
import fastparquet as fp
import pandas as pd
import numpy as np
import shutil as su
print('dask',dask.__version__,'fastparquet',fp.__version__)

if os.path.exists('__fpdasktest.parq'): su.rmtree('__fpdasktest.parq')
df=pd.DataFrame(np.random.randint(0,100,(5,3)),columns=list('abc'))
fp.write('__fpdasktest.parq',df,file_scheme='hive',partition_on=['a'],compression='SNAPPY')

df2=dd.read_parquet('__fpdasktest.parq', filters=[('a','>',10)]).compute()
print(df,'\n',df2)

from dask154 import dataframe as dd
df3=dd.read_parquet('__fpdasktest.parq', filters=[('a','>',10)]).compute()
print(df3)

dask 0.15.2 fastparquet 0.1.3
    a   b   c
0  20  61  24
1  25  31  66
2  71  45  98
3  92  80  66
4  98  42  59 
     b   c   a
0  80  66  92
0  31  66  25
0  42  59  98
0  61  24  20
0  45  98  71
    b   c   a
0  80  66  92
0  31  66  25
0  42  59  98
0  61  24  20
0  45  98  71
```

**Comment by apiszcz** [comment]
Update.... see versions.

```
import os, sys
import dask
from dask import dataframe as dd
import fastparquet as fp
import pandas as pd
import numpy as np
import shutil as su
print('dask',dask.__version__,'fastparquet',fp.__version__)

if os.path.exists('__fpdasktest.parq'): su.rmtree('__fpdasktest.parq')
df=pd.DataFrame(np.random.randint(0,100,(5,3)),columns=list('abc'))
fp.write('__fpdasktest.parq',df,file_scheme='hive',partition_on=['a'],compression='SNAPPY')

df2=dd.read_parquet('__fpdasktest.parq', filters=[('a','>',10)]).compute()
print(df,'\n',df2)

dask 0.15.4 fastparquet 0.1.3




---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-08df67296401> in <module>()
     12 fp.write('__fpdasktest.parq',df,file_scheme='hive',partition_on=['a'],compression='SNAPPY')
     13 
---> 14 df2=dd.read_parquet('__fpdasktest.parq', filters=[('a','>',10)]).compute()
     15 print(df,'\n',df2)

C:\g\via\lib\dask\dataframe\io\parquet.py in read_parquet(path, columns, filters, categories, index, storage_options, engine)
    291         return _read_fastparquet(fs, paths, file_opener, columns=columns,
    292                                  filters=filters,
--> 293                                  categories=categories, index=index)
    294     else:
    295         return _read_pyarrow(fs, paths, file_opener, columns=columns,

C:\g\via\lib\dask\dataframe\io\parquet.py in _read_fastparquet(fs, paths, myopen, columns, filters, categories, index, storage_options)
     61     name = 'read-parquet-' + tokenize(pf, columns, categories)
     62 
---> 63     rgs = [rg for rg in pf.row_groups if
     64            not(fastparquet.api.filter_out_stats(rg, filters, pf.schema)) and
     65            not(fastparquet.api.filter_out_cats(rg, filters))]

C:\g\via\lib\dask\dataframe\io\parquet.py in <listcomp>(.0)
     63     rgs = [rg for rg in pf.row_groups if
     64            not(fastparquet.api.filter_out_stats(rg, filters, pf.schema)) and
---> 65            not(fastparquet.api.filter_out_cats(rg, filters))]
     66 
     67     if index is False:

C:\g\via\lib\fastparquet\api.py in filter_out_cats(rg, filters, sep)
    709             else:
    710                 v0 = val_to_num(v)
--> 711             out = filter_val(op, val, v0, v0)
    712             if out is True:
    713                 return True

C:\g\via\lib\fastparquet\api.py in filter_val(op, val, vmin, vmax)
    735         if op in ['==', '>='] and val > vmax:
    736             return True
--> 737         if op == '>' and val >= vmax:
    738             return True
    739         if op == 'in' and min(val) > vmax:

TypeError: unorderable types: int() >= str()



```

**Comment by apiszcz** [comment]
next test is to download latest fastparquet

**Comment by martindurant** [comment]
Superseded by #271

**Pull request closed without merging**
